import {test} from 'node:test';
import assert from 'node:assert/strict';
import {fixture,legacyDb} from './fixture.mjs';
import {createCatalog} from '../lib/catalog.mjs';
import {createWorkflows} from '../lib/workflows.mjs';
import {createDesk} from '../lib/desk.mjs';
import {createAccounts} from '../lib/accounts.mjs';
import {createIdentity} from '../lib/identity.mjs';
import {createSso} from '../lib/sso.mjs';
import {createExtensions} from '../lib/extensions.mjs';
import {createMail,stripReply} from '../lib/mail.mjs';
import {createWebhooks,allowedAddress} from '../lib/webhooks.mjs';
import {migrateV2,migrateV3,migrateV4} from '../lib/migrations.mjs';
import {migrateV5} from '../lib/migration-v5.mjs';
import {username} from '../lib/usernames.mjs';
import {workingMs,deadline,validateSlaConfig} from '../lib/sla.mjs';
import {secretStore} from '../lib/secrets.mjs';
function setup(){
 const f=fixture();let time=Date.parse('2026-09-14T09:00:00Z');const clock=()=>time;
 const catalog=createCatalog(f.db,f.projects),workflows=createWorkflows(f.db,f.projects,{clock}),desk=createDesk(f.db,f.projects,catalog,workflows,{clock});const sent=[];
 const accounts=createAccounts(f.db,{origin:'https://help.example.test',dataDir:f.dataDir,encodePassword:async p=>'encoded:'+p,transport:{async sendMail(m){sent.push(m);}}});
 const identity=createIdentity(f.db,f.projects,accounts,{origin:'https://help.example.test',encodePassword:async p=>'encoded:'+p,clock}),sso=createSso(f.db,f.projects,{origin:'https://help.example.test',dataDir:f.dataDir,clock});const ext=createExtensions(f.db,f.projects,catalog,workflows,desk,accounts,identity,sso,{origin:'https://help.example.test',dataDir:f.dataDir,clock});
 const project=(key,type='external')=>f.projects.create({key,name:key+' Projekt',project_type:type,portal_access:'authenticated'},f.admin);
 const user=(email,role='customer',name='Adam Dehmel')=>{const id=Number(f.db.prepare("INSERT INTO users(email,name,username,password,role,must_change,created_at) VALUES(?,?,?,'TEST',?,0,?)").run(email,name,email.split('@')[0],role,new Date(time).toISOString()).lastInsertRowid);return f.db.prepare('SELECT * FROM users WHERE id=?').get(id);};
 const ticket=(p,reporter=f.admin)=>{const rt=f.db.prepare("SELECT * FROM request_types WHERE project_id=? AND base_type='incident' ORDER BY id LIMIT 1").get(p.id),form=catalog.prepare(p,{request_type_id:rt.id,request_type_version:rt.version,title:'Problem z kontem',description:'Opis problemu'},false),n=f.projects.project(p.id).next_number,stamp=new Date(time).toISOString();f.db.prepare('UPDATE projects SET next_number=next_number+1 WHERE id=?').run(p.id);const id=Number(f.db.prepare("INSERT INTO tickets(project_id,key,number,title,description,type,priority,status,workflow_status,reporter_id,created_by,created_at,updated_at,request_type_id,form_snapshot,custom_values) VALUES(?,?,?,'Problem z kontem','Opis problemu','incident','P3','open','open',?,?,?,?,?,?,?)").run(p.id,f.projects.issueKey(p,n),n,reporter.id,f.admin.id,stamp,stamp,form.id,form.snapshot,form.values).lastInsertRowid);return desk.ticket(id);};
 const state=(id,to,actor=f.admin,extra={})=>{const t=desk.ticket(id),s=workflows.get(t.project_id).statuses.find(s=>s.key===to);f.db.prepare("UPDATE tickets SET workflow_status=?,status=?,resolution_text=?,updated_at=?,change_source='web',version=version+1 WHERE id=?").run(to,s.category,extra.resolution??t.resolution_text,new Date(time).toISOString(),id);workflows.automation.onChange(t,actor);return desk.ticket(id);};
 const comment=(t,u,body,internal=0)=>Number(f.db.prepare('INSERT INTO comments(ticket_id,author_id,actual_actor_id,body,internal,created_at) VALUES(?,?,?,?,?,?)').run(t.id,u.id,u.id,body,internal,new Date(time).toISOString()).lastInsertRowid);
 return {...f,catalog,workflows,desk,accounts,identity,sso,ext,project,user,ticket,state,comment,sent,clock,advance:n=>time+=n,close(){ext.stop();accounts.stop();workflows.automation.stop();f.close();}};
}
test('Migracja v4 zachowuje dane i nie wymyśla historycznych czasów; jest idempotentna',()=>{const db=legacyDb();try{migrateV2(db);migrateV3(db);migrateV4(db);db.exec("INSERT INTO projects(id,key,name,kind,created_at) VALUES(1,'XX','Projekt','service','2026-01-01'); INSERT INTO project_workflows VALUES(1,'{\"statuses\":[{\"key\":\"closed\",\"name\":\"Zamknięte\",\"category\":\"closed\"}],\"transitions\":[],\"rules\":[]}',1); INSERT INTO tickets(id,project_id,key,title,description,type,priority,status,workflow_status,reporter_id,created_at,updated_at) VALUES(1,1,'XX-1','Test','Opis','incident','P3','closed','closed',1,'2026-01-01','2026-01-03');");migrateV5(db);migrateV5(db);const t=db.prepare('SELECT * FROM tickets').get();assert.equal(t.key,'XX-1');assert.equal(t.tracking_complete,0);assert.equal(t.closed_at,'2026-01-03');assert.equal(db.prepare('PRAGMA foreign_key_check').all().length,0);assert.throws(()=>db.prepare("UPDATE tickets SET status='open',workflow_status='open' WHERE id=1").run(),/DESK_FINAL_CLOSED/);}finally{db.close();}});
test('Zgłaszający, powiązania i firmy respektują granice projektów',()=>{const f=setup();try{const a=f.project('CW'),b=f.project('ITA','internal'),u=f.user('client@example.test'),v=f.user('colleague@example.test'),outsider=f.user('other@example.test'),t=f.ticket(a,u);assert.equal(f.desk.reporter(a,u.id,f.admin),u.id);assert.throws(()=>f.desk.reporter(a,v.id,u),e=>e.status===403);const org=f.ext.resources.saveOrganization(null,{name:'Firma klienta',share_tickets:true,members:[u.id,v.id],projects:[a.id]},f.admin);f.db.prepare('UPDATE tickets SET organization_id=? WHERE id=?').run(org.id,t.id);const shared=f.desk.ticket(t.id);assert.equal(f.projects.canRead(v,a,shared),true);assert.equal(f.projects.canRead(outsider,a,shared),false);const copy=f.desk.clone(t.id,{project_id:b.id},f.admin);assert.equal(copy.reporter_id,u.id);assert.equal(copy.created_by,f.admin.id);assert.equal(f.desk.links(t,f.admin).length,1);assert.deepEqual(f.desk.links(t,u),[]);assert.equal(f.projects.canRead(u,b,copy),false);assert.throws(()=>f.ext.resources.saveOrganization(org.id,{...org,version:org.version,name:'Inne'},u),e=>e.status===403);}finally{f.close();}});
test('Czasy statusów sumują wielokrotne wejścia i zamrażają się po zamknięciu',()=>{const f=setup();try{const p=f.project('TIME'),t=f.ticket(p);f.advance(3600000);f.state(t.id,'waiting');f.advance(2*3600000);f.state(t.id,'open');f.advance(1800000);f.state(t.id,'closed');const result=f.desk.times(f.desk.ticket(t.id));assert.equal(result.total_ms,3.5*3600000);assert.equal(result.statuses.find(s=>s.key==='open').total_ms,1.5*3600000);f.advance(86400000);assert.deepEqual(f.desk.times(f.desk.ticket(t.id)),result);assert.throws(()=>f.state(t.id,'open'),/DESK_FINAL_CLOSED/);}finally{f.close();}});
test('Wymagane rozwiązanie obejmuje zamykanie ręczne i automatyczne',()=>{const f=setup();try{let p=f.project('RES');f.desk.saveSettings(p.id,{version:p.version,resolution_required:true,resolution_statuses:['resolved']},f.admin);const t=f.ticket(p);assert.throws(()=>f.state(t.id,'resolved'),/DESK_RESOLUTION_REQUIRED/);f.state(t.id,'resolved',f.admin,{resolution:'Naprawiono integrację LDAP.'});f.state(t.id,'closed');assert.equal(f.desk.ticket(t.id).resolution_text,'Naprawiono integrację LDAP.');assert.deepEqual(f.workflows.transitions(f.desk.ticket(t.id),true),[]);}finally{f.close();}});
test('Kalendarz SLA uwzględnia weekend, święto, DST i nakładanie przedziałów',()=>{const c=validateSlaConfig({timezone:'Europe/Warsaw',week:{1:[['09:00','17:00']],2:[['09:00','17:00']],3:[['09:00','17:00']],4:[['09:00','17:00']],5:[['09:00','17:00']],6:[],7:[]},holidays:['2026-09-14'],rules:[]},[]);const start=Date.parse('2026-09-11T14:00:00Z'),end=Date.parse('2026-09-15T08:00:00Z');assert.equal(workingMs(start,end,c),2*3600000);assert.equal(deadline(start,2*3600000,c),'2026-09-15T08:00:00.000Z');const all={...c,holidays:[],week:Object.fromEntries([1,2,3,4,5,6,7].map(d=>[d,[['00:00','24:00']]]))};assert.equal(workingMs(Date.parse('2026-10-24T22:00Z'),Date.parse('2026-10-25T23:00Z'),all),25*3600000);assert.throws(()=>validateSlaConfig({...c,week:{...c.week,1:[['09:00','12:00'],['11:00','17:00']]}},[]),e=>e.status===400);});
test('SLA zatrzymuje czas na kliencie i kończy miernik we wskazanym statusie',()=>{const f=setup();try{const p=f.project('SLA'),goals={P1:60,P2:60,P3:60,P4:60};f.desk.saveSettings(p.id,{version:p.version,sla:{timezone:'UTC',rules:[{id:'solve',name:'Naprawa',kind:'status',goals,start:[],pause:['waiting'],stop:['resolved'],reset_on_start:false}]}},f.admin);const t=f.ticket(p);f.advance(30*60000);f.state(t.id,'waiting');f.advance(8*3600000);assert.equal(f.desk.detail(f.desk.ticket(t.id),f.admin).sla[0].state,'paused');f.state(t.id,'in_progress');f.advance(15*60000);f.state(t.id,'resolved');const m=f.desk.detail(f.desk.ticket(t.id),f.admin).sla[0];assert.equal(m.elapsed_ms,45*60000);assert.equal(m.state,'completed');assert.equal(m.breached,false);}finally{f.close();}});
test('Synchronizacja tworzy jedną kopię, podpisuje botem i nie ujawnia notatek klientowi',()=>{const f=setup();try{const a=f.project('CW'),b=f.project('ITA','internal'),client=f.user('client@example.test'),bot=f.db.prepare("SELECT * FROM users WHERE account_kind='service'").get();const r=f.ext.sync.save(null,{name:'Do ITA',source_project:a.id,target_project:b.id,enabled:true,config:{author_id:bot.id,comments:'both',internal_notes:false,to_target:[{from:'waiting',to:'in_progress'}],to_source:[{from:'resolved',to:'resolved'}]}},f.admin),t=f.ticket(a,client);f.comment(t,client,'Pierwszy opis');const copy=f.ext.sync.transfer(t.id,r.id,f.admin);assert.equal(f.ext.sync.transfer(t.id,r.id,f.admin).id,copy.id);f.ext.events();f.comment(copy,f.admin,'Naprawiono konto');f.comment(copy,f.admin,'Tajne dane techniczne',1);f.ext.events();const comments=f.db.prepare('SELECT * FROM comments WHERE ticket_id=?').all(t.id);assert.equal(comments.filter(c=>c.body==='Naprawiono konto').length,1);assert.equal(comments.find(c=>c.body==='Naprawiono konto').author_id,bot.id);assert.equal(comments.find(c=>c.body==='Naprawiono konto').actual_actor_id,f.admin.id);assert.ok(!comments.some(c=>c.body==='Tajne dane techniczne'));f.state(t.id,'waiting');f.ext.events();assert.equal(f.desk.ticket(copy.id).workflow_status,'in_progress');f.state(copy.id,'resolved');f.ext.events();assert.equal(f.desk.ticket(t.id).status,'resolved');const count=f.db.prepare('SELECT COUNT(*) n FROM comments').get().n;f.ext.events();assert.equal(f.db.prepare('SELECT COUNT(*) n FROM comments').get().n,count);assert.equal(f.db.prepare("SELECT COUNT(*) n FROM desk_events WHERE status='failed'").get().n,0);assert.throws(()=>f.ext.sync.transfer(t.id,r.id,client),e=>e.status===404);}finally{f.close();}});
test('Komentarz klienta wyzwala regułę; notatka agenta nie spełnia warunku, bot nie zapętla reguł',()=>{const f=setup();try{const p=f.project('RULE'),client=f.user('reply@example.test'),t=f.ticket(p,client),w=f.workflows.get(p.id);f.workflows.save(p.id,{...w,rules:[{id:'customer',name:'Odpowiedź klienta',enabled:true,event:'comment_added',from:'waiting',match:'all',conditions:[{field:'author_kind',op:'eq',value:'customer'},{field:'comment_body',op:'contains',value:'dalej'}],actions:[{type:'status',value:'in_progress'},{type:'comment',body:'Dziękujemy {{ticket.key}}',internal:false}]}]},f.admin);f.state(t.id,'waiting');f.comment(t,f.admin,'Dalej analizujemy',1);f.ext.events();assert.equal(f.desk.ticket(t.id).status,'waiting');f.comment(t,client,'Problem dalej występuje');f.ext.events();assert.equal(f.desk.ticket(t.id).status,'in_progress');assert.equal(f.db.prepare("SELECT COUNT(*) n FROM comments WHERE origin='automation'").get().n,1);}finally{f.close();}});
test('Zamykający agent lub wybrany bot może zostać przypisany przez regułę',()=>{const f=setup();try{const p=f.project('ASG'),t=f.ticket(p),w=f.workflows.get(p.id);f.workflows.save(p.id,{...w,rules:[{id:'owner',name:'Osoba zamykająca',event:'ticket_closed',from:'closed',enabled:true,match:'all',conditions:[],actions:[{type:'assign',value:'actor'}]}]},f.admin);f.state(t.id,'closed',f.admin);assert.equal(f.desk.ticket(t.id).assignee_id,f.admin.id);}finally{f.close();}});
test('Ukryte pola przyjmują wartości administratora i nie dają się nadpisać klientowi',()=>{const f=setup();try{const p=f.project('FORM'),r=f.catalog.save(p.id,null,{name:'Dostęp VPN',base_type:'request',portal_visible:true,base_fields:{title:{hidden:true,value:'Wniosek o VPN'},description:{hidden:true,value:'Proszę o nadanie dostępu VPN.'}}},f.admin),form=f.catalog.prepare(p,{request_type_id:r.id,request_type_version:r.version,title:'Podmieniony temat',description:'Podmieniony opis'},true);assert.equal(form.title,'Wniosek o VPN');assert.equal(form.description,'Proszę o nadanie dostępu VPN.');assert.throws(()=>f.catalog.save(p.id,null,{name:'Brak wartości',base_fields:{title:{hidden:true,value:''}}},f.admin),e=>e.status===400);}finally{f.close();}});
test('Nazwy kont, zaproszenie jednorazowe, konta serwisowe i zmiana nazwiska przez zatwierdzenie',async()=>{const f=setup();try{assert.equal(username(f.db,'Adam','Dehmel'),'dehmead');const a=await f.identity.create({first_name:'Adam',last_name:'Dehmel',email:'adam@example.test',role:'customer',password:'Strong-demo-password'},f.admin);assert.equal(a.username,'dehmead');assert.equal(a.must_change,0);assert.equal(username(f.db,'Adam','Dehmel'),'dehmeada');assert.equal(username(f.db,'Aleksander','Li'),'lialeks');const req=f.identity.request(a,{kind:'name',first_name:'Adam',last_name:'Nowak'});assert.equal(f.db.prepare('SELECT last_name FROM users WHERE id=?').get(a.id).last_name,'Dehmel');assert.throws(()=>f.identity.review(req.id,{approve:true},a),e=>e.status===403);f.identity.review(req.id,{approve:true},f.admin);assert.equal(f.db.prepare('SELECT username FROM users WHERE id=?').get(a.id).username,'dehmead');const invited=await f.identity.create({first_name:'Ewa',last_name:'Kowalska',email:'ewa@example.test',role:'customer'},f.admin);assert.equal(invited.registration_state,'pending_email');await f.accounts.flush();const raw=f.sent.find(m=>m.to.address==='ewa@example.test').text.match(/invite\/([a-f0-9]{64})/)[1];await f.identity.acceptInvite(raw,'A-new-strong-password');await assert.rejects(()=>f.identity.acceptInvite(raw,'Another-password'),e=>e.status===400);const bot=await f.identity.create({first_name:'Robot',email:'robot@example.test',account_kind:'service'},f.admin);assert.equal(bot.password,'!service');assert.equal(bot.role,'agent');}finally{f.close();}});
test('Zmiana e-mail wymaga kolejno kodu starego i nowego adresu, ogranicza próby i kończy sesje',async()=>{const f=setup();try{const u=f.user('old@example.test'),start=f.identity.emailBegin(u,{email:'new@example.test'});await f.accounts.flush();const old=f.sent.at(-1).text.match(/\b\d{6}\b/)[0];assert.throws(()=>f.identity.emailVerify(u,{token:start.token,code:'000000'}),e=>e.status===400);const phase=f.identity.emailVerify(u,{token:start.token,code:old});assert.equal(phase.step,'new');assert.equal(f.db.prepare('SELECT email FROM users WHERE id=?').get(u.id).email,u.email);await f.accounts.flush();const newer=f.sent.at(-1).text.match(/\b\d{6}\b/)[0];f.db.prepare('INSERT INTO sessions VALUES(?,?,?,?)').run('test',u.id,'csrf',f.clock()+10000);f.identity.emailVerify(u,{token:start.token,code:newer});assert.equal(f.db.prepare('SELECT email FROM users WHERE id=?').get(u.id).email,'new@example.test');assert.equal(f.db.prepare('SELECT COUNT(*) n FROM sessions WHERE user_id=?').get(u.id).n,0);assert.throws(()=>f.identity.emailVerify(u,{token:start.token,code:newer}),e=>e.status===400);}finally{f.close();}});
test('Katalog urządzeń i szablony obiegów respektują dopuszczone projekty',()=>{const f=setup();try{const p=f.project('TKT'),a=f.project('AST','assets'),t=f.ticket(p),client=f.user('asset-client@example.test'),asset=f.ext.resources.saveAsset(null,{project_id:a.id,name:'Laptop CW',kind:'Laptop',serial:'SN-001',data:{Model:'ThinkPad'}},f.admin);assert.throws(()=>f.ext.resources.attach(t.id,asset.id,false,f.admin),e=>e.status===403);f.desk.saveSettings(p.id,{version:f.projects.project(p.id).version,asset_projects:[a.id]},f.admin);f.ext.resources.attach(t.id,asset.id,false,f.admin);assert.equal(f.desk.detail(t,f.admin).assets.length,1);assert.throws(()=>f.ext.resources.assets(client),e=>e.status===403);const template=f.ext.resources.templateSave(null,{project_id:p.id,name:'Mój wzór',is_default:true},f.admin),copy=f.ext.resources.templateClone(template.id,{name:'Kopia wzoru'},f.admin);assert.notEqual(copy.id,template.id);assert.equal(copy.is_default,0);}finally{f.close();}});
test('Poczta: nowa sprawa, odpowiedź w wątku, deduplikacja, blokada obcego nadawcy i zamkniętej sprawy',async()=>{const f=setup();try{const p=f.project('MAIL'),u=f.user('sender@example.test'),r=f.db.prepare("SELECT id FROM request_types WHERE project_id=? AND base_type='incident'").get(p.id),channel=f.ext.mail.save(null,{project_id:p.id,name:'Wsparcie',email:'support@example.test',enabled:true,config:{imap_host:'mail.example.test',imap_user:'support',imap_pass:'secret',smtp_host:'mail.example.test',smtp_user:'support',smtp_pass:'secret',request_type_id:r.id}},f.admin);const raw=(from,id,subject,body,headers='')=>Buffer.from(`From: ${from}\r\nTo: support@example.test\r\nSubject: ${subject}\r\nMessage-ID: <${id}@example.test>\r\n${headers}MIME-Version: 1.0\r\nContent-Type: text/plain; charset=utf-8\r\n\r\n${body}`);const first=await f.ext.mail.ingest(channel.id,'1',1,raw(u.email,'first','Problem z VPN','Proszę o pomoc z VPN.'));assert.equal(first.status,'processed');const t=f.desk.ticket(first.ticket_id);f.ext.events();assert.equal(f.db.prepare('SELECT COUNT(*) n FROM mail_outbox WHERE ticket_id=?').get(t.id).n,1);const reply=await f.ext.mail.ingest(channel.id,'1',2,raw(u.email,'reply','Re: Problem z VPN','Nadal nie działa\nOdpowiedz powyżej tej linii\nStara treść','In-Reply-To: <first@example.test>\r\n'));assert.equal(reply.ticket_id,t.id);assert.equal(f.db.prepare('SELECT body FROM comments WHERE ticket_id=?').get(t.id).body,'Nadal nie działa');await f.ext.mail.ingest(channel.id,'2',1,raw(u.email,'reply','Re: Problem','Duplikat'));assert.equal(f.db.prepare('SELECT COUNT(*) n FROM comments').get().n,1);const bad=await f.ext.mail.ingest(channel.id,'2',2,raw('stranger@example.test','bad','['+t.key+'] Problem','Podmieniona odpowiedź'));assert.equal(bad.status,'ignored');f.state(t.id,'closed');const late=await f.ext.mail.ingest(channel.id,'2',3,raw(u.email,'late','['+t.key+'] Problem','Jeszcze jedna odpowiedź'));assert.equal(late.status,'ignored');assert.match(late.detail,/Zamknięta/);const auto=await f.ext.mail.ingest(channel.id,'2',4,raw(u.email,'auto','Automatyczna','Nieobecność','Auto-Submitted: auto-replied\r\n'));assert.equal(auto.status,'ignored');assert.equal(stripReply('Tekst\n> Odpowiedz powyżej tej linii\n> cytat'),'Tekst');}finally{f.close();}});
test('Webhook: podpisany outbox, unikalny event_id i odrzucenie nieautoryzowanych żądań',async()=>{const f=setup();let sent=[];const hooks=createWebhooks(f.db,f.projects,f.desk,f.workflows,{dataDir:f.dataDir,clock:f.clock,send:async(...args)=>sent.push(args)});try{const p=f.project('HOOK'),t=f.ticket(p),bot=f.db.prepare("SELECT id FROM users WHERE account_kind='service'").get(),incoming=hooks.save(null,{project_id:p.id,name:'Przychodzący',direction:'inbound',config:{bot_id:bot.id}},f.admin);assert.throws(()=>hooks.incoming(incoming.id,'Bearer wrong',{event_id:'e1',ticket_key:t.key}),e=>e.status===401);assert.equal(hooks.incoming(incoming.id,'Bearer '+incoming.generated_secret,{event_id:'e1',ticket_key:t.key}).ok,true);assert.equal(hooks.incoming(incoming.id,'Bearer '+incoming.generated_secret,{event_id:'e1',ticket_key:t.key}).duplicate,true);const out=hooks.save(null,{project_id:p.id,name:'Powiadomienia',direction:'outbound',config:{url:'https://example.test/hook',events:['ticket_created']}},f.admin);hooks.enqueue(out.id,t,'ticket_created',f.admin.id);await hooks.flush();assert.equal(sent.length,1);assert.match(sent[0][2]['X-iTELade-Signature'],/^sha256=[a-f0-9]{64}$/);assert.equal(allowedAddress('127.0.0.1',true),false);assert.equal(allowedAddress('169.254.169.254',true),false);assert.equal(allowedAddress('10.200.0.20',false),false);assert.equal(allowedAddress('10.200.0.20',true),true);assert.equal(allowedAddress('::ffff:127.0.0.1',true),false);}finally{hooks.stop();f.close();}});

test('Awaria synchronizacji nie blokuje e-maila, a ponowienie nie duplikuje zakończonych modułów',()=>{const f=setup();try{const p=f.project('EVT'),t=f.ticket(p),original=f.ext.sync.process;let calls=0;f.ext.sync.process=()=>{calls++;throw Object.assign(new Error('Test awarii mapowania'),{status:409});};f.ext.events();const event=f.db.prepare("SELECT * FROM desk_events WHERE ticket_id=? AND event='ticket_created'").get(t.id);assert.equal(event.status,'failed');assert.equal(f.db.prepare('SELECT COUNT(*) n FROM mail_outbox WHERE ticket_id=?').get(t.id).n,1);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM desk_event_deliveries WHERE event_id=?').get(event.id).n,4);f.ext.sync.process=original;f.db.prepare("UPDATE desk_events SET status='queued' WHERE id=?").run(event.id);f.ext.events();assert.equal(f.db.prepare('SELECT status FROM desk_events WHERE id=?').get(event.id).status,'done');assert.equal(f.db.prepare('SELECT COUNT(*) n FROM mail_outbox WHERE ticket_id=?').get(t.id).n,1);assert.equal(calls,1);}finally{f.close();}});

test('IMAP zachowuje kursor po restarcie i UIDVALIDITY; SMTP zachowuje wątek i bezpieczny HTML',async()=>{const f=setup();let mail;try{const p=f.project('POLL'),u=f.user('poll@example.test'),form=f.db.prepare('SELECT id FROM request_types WHERE project_id=? ORDER BY id LIMIT 1').get(p.id);let validity=11,next=2,items=new Map(),fetches=[],sent=[];
 const raw=id=>Buffer.from(`From: ${u.email}\r\nTo: desk@example.test\r\nSubject: Problem <script>\r\nMessage-ID: <${id}@example.test>\r\nContent-Type: text/plain; charset=utf-8\r\n\r\nProszę o pomoc z kontem.`);
 const opts={origin:'https://help.example.test',dataDir:f.dataDir,clock:f.clock,imapFactory:()=>({mailbox:{uidValidity:validity,uidNext:next},async connect(){},async getMailboxLock(){return {release(){}};},async fetchAll(range){fetches.push(range);const [lo,hi]=range.split(':').map(Number);return [...items].filter(([uid])=>uid>=lo&&uid<=hi).map(([uid,source])=>({uid,size:source.length}));},async fetchOne(uid){return {source:items.get(uid)};},async logout(){},close(){}}),transportFactory:cfg=>({async sendMail(m){assert.equal(cfg.requireTLS,true);assert.equal(cfg.tls.rejectUnauthorized,true);sent.push(m);},close(){}})};
 mail=createMail(f.db,f.projects,f.catalog,f.workflows,f.desk,f.accounts,opts);const channel=mail.save(null,{project_id:p.id,name:'Centrum Wsparcia',email:'desk@example.test',enabled:true,config:{imap_host:'mail.example.test',imap_user:'desk',imap_pass:'secret',smtp_host:'mail.example.test',smtp_user:'desk',smtp_pass:'secret',request_type_id:form.id,start_from_now:true}},f.admin);items.set(1,raw('old'));await mail.poll();assert.equal(fetches.length,0);assert.equal(f.db.prepare('SELECT uid_cursor FROM email_channels').get().uid_cursor,1);
 items.set(2,raw('new'));next=3;await mail.poll();assert.equal(f.db.prepare('SELECT COUNT(*) n FROM tickets WHERE project_id=?').get(p.id).n,1);mail.stop();mail=createMail(f.db,f.projects,f.catalog,f.workflows,f.desk,f.accounts,opts);await mail.poll();assert.equal(fetches.length,1);validity=12;items=new Map([[1,raw('new')]]);next=2;await mail.poll();assert.equal(f.db.prepare('SELECT COUNT(*) n FROM tickets WHERE project_id=?').get(p.id).n,1);assert.equal(f.db.prepare('SELECT uidvalidity FROM email_channels').get().uidvalidity,'12');
 f.ext.events();await mail.flush();assert.equal(sent.length,1);assert.equal(sent[0].replyTo.address,'desk@example.test');assert.equal(sent[0].inReplyTo,'<new@example.test>');assert.match(sent[0].html,/&lt;script&gt;/);assert.ok(!sent[0].html.includes('<script>'));assert.match(sent[0].text,/Odpowiedz powyżej tej linii/);assert.equal(sent[0].headers['Auto-Submitted'],'auto-generated');assert.equal(f.db.prepare('SELECT status FROM mail_outbox WHERE channel_id=?').get(channel.id).status,'sent');
 }finally{mail?.stop();f.close();}});

test('Numeracja urządzeń: klucz i format są stałe, licznik nie może się cofać',()=>{const f=setup();try{let p=f.project('DEV','assets');const a=f.ext.resources.saveAsset(null,{project_id:p.id,name:'Komputer',kind:'Laptop'},f.admin);p=f.projects.project(p.id);for(const change of [{next_number:1},{key:'SPRZ'},{number_padding:4}])assert.throws(()=>f.projects.update(p.id,{version:p.version,...change},f.admin),e=>e.status===409);const b=f.ext.resources.saveAsset(null,{project_id:p.id,name:'Drugi komputer',kind:'Laptop'},f.admin);assert.equal(f.ext.resources.assets(f.admin,p.id).find(x=>x.id===a.id).asset_key,a.asset_key);assert.notEqual(a.asset_key,b.asset_key);}finally{f.close();}});
