import test from 'node:test';
import assert from 'node:assert/strict';
import {fixture} from './fixture.mjs';
import {migrateV8} from '../lib/migration-v8.mjs';
import {createCatalog} from '../lib/catalog.mjs';
import {createWorkflows} from '../lib/workflows.mjs';
import {createDesk} from '../lib/desk.mjs';
import {createV8} from '../lib/v8.mjs';
function response(code,value){return {ok:code>=200&&code<300,status:code,async text(){return JSON.stringify(value);}};}
function setup(){const f=fixture();migrateV8(f.db);const catalog=createCatalog(f.db,f.projects),workflows=createWorkflows(f.db,f.projects),desk=createDesk(f.db,f.projects,catalog,workflows);const p=f.projects.create({key:'GHA',name:'GitHub Auto',project_type:'external',portal_access:'authenticated'},f.admin),rt=f.db.prepare('SELECT * FROM request_types WHERE project_id=? AND enabled=1 ORDER BY id LIMIT 1').get(p.id);f.db.prepare("INSERT INTO sso_providers(name,issuer,client_id,secret,config,enabled) VALUES('GitHub','https://github.com/','client','secret','{\"auto_create\":false,\"allowed_domains\":[],\"provider_type\":\"github\"}',1)").run();let closed=0,commented=0;const issue={id:9001,number:77,title:'Broken login',body:'Please fix',html_url:'https://github.com/acme/widget/issues/77',labels:[],user:{id:12345,login:'alice'}};const fetcher=async(url,opt={})=>{if(url.includes('/issues?'))return response(200,[issue]);if(url.endsWith('/users/alice'))return response(200,{id:12345,login:'alice',name:'Alice Example',email:null});if(url.endsWith('/issues/77/comments')){commented++;return response(201,{});}if(url.endsWith('/issues/77')&&opt.method==='PATCH'){closed++;return response(200,{});}return response(200,{full_name:'acme/widget'});};const v8=createV8(f.db,{projects:f.projects,desk,workflows,catalog,accounts:{settings:()=>({smtp_configured:false})},dataDir:f.dataDir,origin:'https://desk.example.test',fetcher});const body={name:'GitHub intake',owner:'acme',repo:'widget',project_id:p.id,request_type_id:rt.id,reporter_id:f.admin.id,token:'github-token-test',label_priority:{},comment_template:'Moved: {ticket_url}',poll_minutes:5,enabled:true};return Promise.resolve(v8.handle('POST','/api/desk/v8/github',f.admin,new URLSearchParams(),async()=>body)).then(()=>({...f,p,rt,v8,workflows,getCounts:()=>({closed,commented}),close(){workflows.automation.stop();f.close();}}));}
test('GitHub Issue auto-creates a customer account mapped to immutable GitHub user id',async()=>{const f=await setup();try{await f.v8.background();const map=f.db.prepare("SELECT s.subject,u.* FROM sso_subjects s JOIN sso_providers p ON p.id=s.provider_id JOIN users u ON u.id=s.user_id WHERE p.issuer='https://github.com/'").get();assert.equal(map.subject,'12345');assert.equal(map.role,'customer');assert.equal(map.sso_only,1);assert.equal(map.registration_state,'active');assert.match(map.email,/\.invalid$/);const ticket=f.db.prepare("SELECT * FROM tickets WHERE origin='github'").get();assert.equal(ticket.reporter_id,map.id);assert.equal(ticket.created_by,f.admin.id);assert.ok(f.db.prepare("SELECT 1 FROM project_members WHERE project_id=? AND user_id=? AND role='requester'").get(f.p.id,map.id));assert.deepEqual(f.getCounts(),{closed:1,commented:1});}finally{f.close();}});
