import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {directoryDefaults,normalizeEntry} from '../lib/directory.mjs';
import {VERSION,SCHEMA_VERSION} from '../lib/version.mjs';
import {fixture} from './fixture.mjs';
import {migrateV8} from '../lib/migration-v8.mjs';
import {createCatalog} from '../lib/catalog.mjs';
import {createWorkflows} from '../lib/workflows.mjs';
import {createDesk} from '../lib/desk.mjs';
import {createV8} from '../lib/v8.mjs';

const source=p=>readFileSync(new URL('../'+p,import.meta.url),'utf8');
const response=(status,body)=>({ok:status>=200&&status<300,status,async text(){return body===undefined?'':JSON.stringify(body);}});

function setupV8(fetcher=async()=>response(200,{}),catalogDecorator=null){
  const f=fixture();migrateV8(f.db);
  const baseCatalog=createCatalog(f.db,f.projects),catalog=catalogDecorator?catalogDecorator(baseCatalog):baseCatalog;
  const workflows=createWorkflows(f.db,f.projects),desk=createDesk(f.db,f.projects,catalog,workflows);
  const project=f.projects.create({key:'GH1',name:'GitHub Intake',project_type:'external',portal_access:'authenticated'},f.admin);
  const requestType=f.db.prepare('SELECT * FROM request_types WHERE project_id=? AND enabled=1 ORDER BY id LIMIT 1').get(project.id);
  const v8=createV8(f.db,{projects:f.projects,desk,workflows,catalog,dataDir:f.dataDir,origin:'https://desk.example.test',fetcher});
  const call=async(method,path,user=f.admin,body={},query='')=>(await v8.handle(method,path,user,new URLSearchParams(query),async()=>body)).value;
  const integrationBody=(extra={})=>({name:'Public issues',owner:'acme',repo:'widget',project_id:project.id,request_type_id:requestType.id,reporter_id:f.admin.id,token:'github-token-for-tests',label_priority:{critical:'P1'},comment_template:'Moved to {ticket_url}',poll_minutes:1,enabled:true,...extra});
  return {...f,catalog,workflows,desk,project,requestType,v8,call,integrationBody,close(){workflows.automation.stop();f.close();}};
}

function user(f,email,role='agent'){
  const id=Number(f.db.prepare("INSERT INTO users(email,name,username,password,role,must_change,active,created_at) VALUES(?,?,?,?,?,0,1,?)").run(email,email,email.split('@')[0],'TEST',role,new Date().toISOString()).lastInsertRowid);
  return f.db.prepare('SELECT * FROM users WHERE id=?').get(id);
}

test('1.0.1 version and cache busting are consistent',()=>{assert.equal(VERSION,'1.0.1');assert.equal(SCHEMA_VERSION,8);const pkg=JSON.parse(source('package.json')),lock=JSON.parse(source('package-lock.json')),index=source('public/index.html'),admin=source('public/v8.html');assert.equal(pkg.version,'1.0.1');assert.equal(lock.version,'1.0.1');assert.equal(lock.packages[''].version,'1.0.1');for(const html of [index,admin]){assert.doesNotMatch(html,/\?v=(?:0\.8\.[01]|1\.0\.0)/);assert.match(html,/\?v=1\.0\.1/);}});

test('fixed role model ignores legacy custom global role tables and API is unavailable',async()=>{const f=setupV8();try{const agent=user(f,'agent@example.test','agent');const customer=user(f,'customer@example.test','customer');const manager=user(f,'manager@example.test','agent');f.db.prepare("INSERT INTO project_members(project_id,user_id,role) VALUES(?,?,'agent')").run(f.project.id,agent.id);f.db.prepare("INSERT INTO project_members(project_id,user_id,role) VALUES(?,?,'requester')").run(f.project.id,customer.id);f.db.prepare("INSERT INTO project_members(project_id,user_id,role) VALUES(?,?,'manager')").run(f.project.id,manager.id);const legacyRole=Number(f.db.prepare("INSERT INTO v8_roles(name,permissions,created_at,updated_at) VALUES('Legacy elevated','["*"]',datetime('now'),datetime('now'))").run().lastInsertRowid);f.db.prepare('INSERT INTO v8_user_roles(user_id,role_id) VALUES(?,?)').run(customer.id,legacyRole);assert.equal(f.v8.fixedRole(f.admin),'global_administrator');assert.equal(f.v8.fixedRole(manager),'project_manager');assert.equal(f.v8.fixedRole(agent),'agent');assert.equal(f.v8.fixedRole(customer),'customer');assert.deepEqual(f.v8.effectivePermissions(customer),[]);await assert.rejects(()=>f.call('GET','/api/desk/v8/roles',f.admin),e=>e.status===404);}finally{f.close();}});

test('Project Manager, Agent and Customer are isolated to allowed project scope',async()=>{const f=setupV8();try{const other=f.projects.create({key:'GH2',name:'Other project',project_type:'external',portal_access:'authenticated'},f.admin),manager=user(f,'manager2@example.test'),agent=user(f,'agent2@example.test'),customer=user(f,'customer2@example.test','customer');f.db.prepare("INSERT INTO project_members(project_id,user_id,role) VALUES(?,?,'manager')").run(f.project.id,manager.id);f.db.prepare("INSERT INTO project_members(project_id,user_id,role) VALUES(?,?,'agent')").run(f.project.id,agent.id);f.db.prepare("INSERT INTO project_members(project_id,user_id,role) VALUES(?,?,'requester')").run(f.project.id,customer.id);for(const [pid,name] of [[f.project.id,'Allowed'],[other.id,'Forbidden']])f.db.prepare("INSERT INTO v8_approval_schemes(project_id,name,stages,enabled,created_at,updated_at) VALUES(?,?,'[]',1,datetime('now'),datetime('now'))").run(pid,name);const schemes=await f.call('GET','/api/desk/v8/approval-schemes',manager);assert.deepEqual(schemes.map(x=>x.project_id),[f.project.id]);const dash=await f.call('GET','/api/desk/v8/dashboard',agent);assert.equal(dash.projects,1);await assert.rejects(()=>f.call('GET','/api/desk/v8/approval-schemes',agent),e=>e.status===403);await assert.rejects(()=>f.call('GET','/api/desk/v8/summary',customer),e=>e.status===403);}finally{f.close();}});

test('fixed LDAP role model maps Global Administrator and project membership',()=>{const c={...directoryDefaults,mappings:[{group_dn:'CN=PM,DC=example,DC=test',project_id:7,role:'manager'}],global_admin_group_dns:['CN=Admins,DC=example,DC=test']};const base={dn:'CN=Alice,DC=example,DC=test',objectGUID:'abc',sAMAccountName:'alice',mail:'alice@example.test',displayName:'Alice',memberOf:['CN=PM,DC=example,DC=test']};const pm=normalizeEntry(base,c);assert.equal(pm.role,'agent');assert.deepEqual(pm.memberships,[{project_id:7,role:'manager'}]);const admin=normalizeEntry({...base,memberOf:['CN=Admins,DC=example,DC=test']},c);assert.equal(admin.role,'admin');});

test('GitHub integration CRUD, request-type dropdown, toggle, test and delete work',async()=>{let tested=false;const f=setupV8(async(url)=>{if(url.endsWith('/repos/acme/widget')){tested=true;return response(200,{full_name:'acme/widget',private:false});}return response(200,[]);});try{const opts=await f.call('GET','/api/desk/v8/github-options',f.admin,{},'project_id='+f.project.id);assert.ok(opts.request_types.some(x=>x.id===f.requestType.id&&x.name===f.requestType.name));assert.ok(opts.reporters.some(x=>x.id===f.admin.id));const created=await f.call('POST','/api/desk/v8/github',f.admin,f.integrationBody());assert.equal(created.auto_close,1);const edited=await f.call('POST','/api/desk/v8/github/'+created.id,f.admin,f.integrationBody({name:'Edited',token:''}));assert.equal(edited.name,'Edited');const testedResult=await f.call('POST','/api/desk/v8/github/'+created.id+'/test',f.admin,{});assert.equal(testedResult.ok,true);assert.equal(tested,true);const disabled=await f.call('POST','/api/desk/v8/github/'+created.id+'/toggle',f.admin,{enabled:false});assert.equal(disabled.enabled,0);const enabled=await f.call('POST','/api/desk/v8/github/'+created.id+'/toggle',f.admin,{enabled:true});assert.equal(enabled.enabled,1);assert.deepEqual(await f.call('POST','/api/desk/v8/github/'+created.id+'/delete',f.admin,{}),{ok:true});assert.equal((await f.call('GET','/api/desk/v8/github')).length,0);}finally{f.close();}});

test('GitHub transfer creates one ticket, comments with link, closes and deduplicates',async()=>{let comments=0,closes=0;const issue={id:101,number:7,html_url:'https://github.com/acme/widget/issues/7',title:'Broken login',body:'Cannot sign in',labels:[{name:'critical'}],user:{login:'alice'}};const f=setupV8(async(url,opt={})=>{if(url.includes('/issues?state=open'))return response(200,[issue]);if(url.endsWith('/issues/7/comments')&&opt.method==='POST'){comments++;return response(201,{id:900});}if(url.endsWith('/issues/7')&&opt.method==='PATCH'){closes++;return response(200,{state:'closed'});}throw new Error('Unexpected GitHub request '+url);});try{const integration=await f.call('POST','/api/desk/v8/github',f.admin,f.integrationBody());await f.v8.background();const ticket=f.db.prepare("SELECT * FROM tickets WHERE origin='github'").get();assert.ok(ticket);assert.equal(ticket.priority,'P1');assert.match(ticket.description,/GitHub issue ID: 101/);assert.match(ticket.description,/https://github.com/acme/widget/issues/7/);let link=f.db.prepare('SELECT * FROM v8_github_links WHERE integration_id=? AND issue_id=?').get(integration.id,101);assert.equal(link.status,'done');assert.equal(comments,1);assert.equal(closes,1);f.db.prepare('UPDATE v8_github_integrations SET last_poll=0 WHERE id=?').run(integration.id);await f.v8.background();assert.equal(f.db.prepare("SELECT COUNT(*) n FROM tickets WHERE origin='github'").get().n,1);assert.equal(comments,1);assert.equal(closes,1);}finally{f.close();}});

test('GitHub comment failure leaves issue open and transfer retry-safe',async()=>{let comments=0,closes=0,commentFails=true,closeFails=false;const issue={id:202,number:8,html_url:'https://github.com/acme/widget/issues/8',title:'Import me',body:'Body',labels:[],user:{login:'bob'}};const f=setupV8(async(url,opt={})=>{if(url.includes('/issues?state=open'))return response(200,[issue]);if(url.endsWith('/issues/8/comments')&&opt.method==='POST'){comments++;return commentFails?response(500,{message:'comment failed'}):response(201,{id:1});}if(url.endsWith('/issues/8')&&opt.method==='PATCH'){closes++;return closeFails?response(500,{message:'close failed'}):response(200,{state:'closed'});}throw new Error('Unexpected GitHub request '+url);});try{const integration=await f.call('POST','/api/desk/v8/github',f.admin,f.integrationBody());await f.v8.background();let link=f.db.prepare('SELECT * FROM v8_github_links WHERE integration_id=?').get(integration.id);assert.equal(link.status,'ticket_created');assert.equal(closes,0);commentFails=false;closeFails=true;f.db.prepare('UPDATE v8_github_integrations SET last_poll=0 WHERE id=?').run(integration.id);await f.v8.background();link=f.db.prepare('SELECT * FROM v8_github_links WHERE id=?').get(link.id);assert.equal(link.status,'commented');assert.equal(comments,2);assert.equal(closes,1);closeFails=false;f.db.prepare('UPDATE v8_github_integrations SET last_poll=0 WHERE id=?').run(integration.id);await f.v8.background();link=f.db.prepare('SELECT * FROM v8_github_links WHERE id=?').get(link.id);assert.equal(link.status,'done');assert.equal(comments,2);assert.equal(closes,2);}finally{f.close();}});

test('GitHub ticket creation failure never comments or closes the source issue',async()=>{let comments=0,closes=0;const issue={id:303,number:9,html_url:'https://github.com/acme/widget/issues/9',title:'Do not close',body:'Body',labels:[],user:{login:'carol'}};const f=setupV8(async(url,opt={})=>{if(url.includes('/issues?state=open'))return response(200,[issue]);if(url.endsWith('/comments')&&opt.method==='POST'){comments++;return response(201,{});}if(opt.method==='PATCH'){closes++;return response(200,{});}return response(200,{});},catalog=>({...catalog,prepare(){throw new Error('ticket creation failed');}}));try{await f.call('POST','/api/desk/v8/github',f.admin,f.integrationBody());await f.v8.background();assert.equal(f.db.prepare("SELECT COUNT(*) n FROM tickets WHERE origin='github'").get().n,0);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM v8_github_links').get().n,0);assert.equal(comments,0);assert.equal(closes,0);}finally{f.close();}});

test('GitHub Administration provides named dropdowns, CRUD controls and readable history',()=>{const ui=source('public/v8.js');assert.match(ui,/Request type<select/);assert.doesNotMatch(ui,/Request type ID<input/);assert.match(ui,/data-github-edit/);assert.match(ui,/data-github-test/);assert.match(ui,/data-github-toggle/);assert.match(ui,/data-github-delete/);assert.match(ui,/Transfer history/);assert.doesNotMatch(ui,/JSON\.stringify\(runs\.slice/);});

test('settings entry point and Administration categories are 1.0.1',()=>{const index=source('public/index.html'),admin=source('public/v8.html');assert.ok(index.includes("location.replace('/v8.html#overview')"));for(const name of ['General','Identity & access','Service management','Communication','Integrations','Assets / CMDB','System'])assert.match(admin,new RegExp(name.replace('/','\\/'),'i'));assert.doesNotMatch(admin,/0\.8 Control Center/i);});
