import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const read=p=>readFileSync(new URL('../'+p,import.meta.url),'utf8');
const index=read('public/index.html'),base=read('public/app.css'),legacy=read('public/release-1.2.0.js'),features=read('public/release-1.1.2.js'),shell=read('public/product-shell.js'),design=read('public/design-system.css'),version=read('lib/version.mjs');
test('2.0 product boundary includes schema 9 migration',()=>{assert.match(version,/VERSION='2\.0\.1'/);assert.match(version,/SCHEMA_VERSION=9/);assert.match(index,/\?v=2\.0\.1/);});
test('2.0 keeps required operational behavior while replacing the visual stack',()=>{for(const token of ['installGlobalSearch','installQueueTools','installAttachments','queue-preferences'])assert.match(features,new RegExp(token));assert.ok(index.includes('/release-1.1.2.js?v=2.0.1'));assert.ok(!index.includes('/release-1.1.2.css?v='));});
test('2.0 service navigation and workspaces are represented by the product shell',()=>{for(const token of ['Service management','Customers & people','Administration','sd20-queue-workspace','sd20-ticket-workspace','sd20-project-settings','sd20-customer-portal'])assert.ok(shell.includes(token),token);});
test('2.0 queue and ticket foundations retain 1.x functional rebuild paths',()=>{assert.match(legacy,/rebuildQueue/);assert.match(legacy,/rebuildTicket/);for(const token of ['.sd20-queue-table','.sd20-ticket-layout','.sd20-inspector'])assert.ok(design.includes(token),token);});
test('2.0 Administration Center has a dedicated searchable navigation surface',()=>{for(const token of ['sd20-settings-center','sd20-settings-nav','sd20-settings-search'])assert.ok(shell.includes(token)||design.includes('.'+token),token);});
test('2.0 retires active 1.2 and 1.6 presentation decorators',()=>{for(const retired of ['release-1.1.2.css','release-1.2.0.js','agent-experience-1.6.css','agent-experience-1.6.js'])assert.doesNotMatch(index,new RegExp(retired.replaceAll('.','\\.')));assert.match(design,/--sd20-bg/);assert.match(base,/Service Desk 2\.0\.1/);});
