import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,existsSync,rmSync,readFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import {createEngine} from '../updater/engine.mjs';
const id='12345678-1234-1234-1234-123456789abc';
function fixture(failure){const root=mkdtempSync(join(tmpdir(),'desk-updater-')),dataDir=join(root,'data'),controlDir=join(root,'control'),backupDir=join(root,'backups');mkdirSync(dataDir);const file=join(dataDir,'desk.sqlite');let db=new DatabaseSync(file);db.exec("CREATE TABLE preserved(value TEXT);INSERT INTO preserved VALUES('before');");db.close();let current='old',image='old-image',calls=[],states={old:{Id:'old',Name:'/desk',Image:image,Config:{Labels:{'com.service-desk.managed':'1'}},Mounts:[{Destination:'/app/data'},{Destination:'/app/control'}],State:{Running:true,Health:{Status:'healthy'}}}};
const docker={async inspect(key){if(key==='desk')key=current;if(!states[key])throw Object.assign(new Error('Missing'),{status:404});return structuredClone(states[key]);},async pull(){calls.push('pull');if(failure==='pull')throw new Error('Registry unavailable');},async stop(key){calls.push('stop:'+key);states[key].State.Running=false;},async rename(key,name){calls.push('rename:'+key);states[key].Name='/'+name;if(name==='desk')current=key;else if(current===key)current=null;},async create(){calls.push('create');if(failure==='create')throw new Error('Cannot create');current='new';states.new={Id:'new',Name:'/desk',State:{Running:false,Health:{Status:'healthy'}}};return {Id:'new'};},async start(key){calls.push('start:'+key);states[key].State.Running=true;if(key==='new'){const db=new DatabaseSync(file);db.exec("UPDATE preserved SET value='after';");db.close();if(failure==='start')throw new Error('Migration failed');}},async remove(key){calls.push('remove:'+key);delete states[key];if(current===key)current=null;},async tag(next){image=next;}};
const engine=createEngine({docker,dataDir,controlDir,backupDir,target:'desk',preserveOwner:false,release:async()=>({version:'0.7.0',minimum_schema:6,schema:7,image:'new-image'}),fetcher:async()=>({ok:true,json:async()=>({version:'0.7.0',schema:7})}),wait:async()=>{}});
return {root,dataDir,controlDir,engine,calls,states,get current(){return current;},get image(){return image;},value(){const d=new DatabaseSync(file);try{return d.prepare('SELECT value FROM preserved').get().value;}finally{d.close();}},close(){rmSync(root,{recursive:true,force:true});}};}
const request={id,repo:'owner/desk',tag:'v0.7.0',version:'0.7.0',current_version:'0.6.0',schema:6,token:''};
test('Aktualizator: błąd pobierania nie zatrzymuje działającej aplikacji',async()=>{const f=fixture('pull');try{await f.engine.run(request);assert.equal(f.engine.read('status.json').phase,'failed');assert.equal(f.value(),'before');assert.ok(f.states.old.State.Running);assert.ok(!f.calls.includes('stop:old'));assert.ok(!existsSync(join(f.controlDir,'maintenance.json')));}finally{f.close();}});
test('Aktualizator: udane wydanie zachowuje kopię i zatwierdza dopiero po zdrowiu',async()=>{const f=fixture();try{await f.engine.run(request);assert.equal(f.engine.read('status.json').phase,'done');assert.equal(f.current,'new');assert.equal(f.image,'new-image');assert.equal(f.value(),'after');assert.ok(existsSync(join(f.engine.read('status.json').backup,'desk.sqlite')));assert.ok(!existsSync(join(f.controlDir,'maintenance.json')));assert.ok(f.calls.indexOf('stop:old')<f.calls.indexOf('create'));}finally{f.close();}});
for(const failure of ['create','start'])test('Aktualizator: '+failure+' przywraca poprzedni kontener i spójną bazę',async()=>{const f=fixture(failure);try{await f.engine.run(request);assert.equal(f.engine.read('status.json').phase,'rolled_back');assert.equal(f.current,'old');assert.equal(f.image,'old-image');assert.equal(f.value(),'before');assert.ok(f.states.old.State.Running);assert.ok(!existsSync(join(f.controlDir,'maintenance.json')));}finally{f.close();}});
test('Aktualizator: restart po zatwierdzeniu kończy zadanie bez cofania przyjętych danych',async()=>{const f=fixture();try{f.engine.write('journal.json',{...request,phase:'committed'});f.engine.write('maintenance.json',{id});await f.engine.recover();assert.equal(f.engine.read('status.json').phase,'done');assert.equal(f.calls.length,0);assert.ok(!existsSync(join(f.controlDir,'maintenance.json')));}finally{f.close();}});
