import {now,fail,txFor,text,integer,boolean,choice} from './core.mjs';
import {createSla,validateSlaConfig} from './sla.mjs';
export function createDesk(db,projects,catalog,workflows,{clock=Date.now}={}){
  const tx=txFor(db),sla=createSla(db,projects,{clock}),stamp=()=>new Date(clock()).toISOString();
  const ticket=id=>db.prepare('SELECT * FROM tickets WHERE id=?').get(integer(Number(id),'Zgłoszenie'));
  const settings=p=>JSON.parse(p.settings||'{}');
  function requireTicket(id,u){const t=ticket(id);if(!t||t.deleted_at||!projects.canWork(u,projects.project(t.project_id)))fail(404,'Zgłoszenie niedostępne.');return t;}
  function reporter(p,id,u){
    integer(id,'Zgłaszający');if(!projects.canWork(u,p))fail(403,'Zmiana zgłaszającego jest dostępna zespołowi.');
    const target=db.prepare("SELECT * FROM users WHERE id=? AND active=1 AND directory_active=1 AND registration_state='active' AND account_kind='human'").get(id);
    if(!target||(p.project_type==='external'&&!projects.canPortal(target,p)))fail(400,'Zgłaszający musi mieć aktywne konto i dostęp do portalu tego projektu.');return id;
  }
  function organization(p,userId,id){
    if(id===null)return null;integer(id,'Organizacja');if(!db.prepare('SELECT 1 FROM organization_members m JOIN project_organizations po ON po.organization_id=m.organization_id WHERE m.organization_id=? AND m.user_id=? AND po.project_id=?').get(id,userId,p.id))fail(400,'Organizacja musi obejmować zgłaszającego i projekt.');return id;
  }
  function reporters(p,u,q=''){projects.requireProject(p.id,u);q=text(q,'Szukaj',0,100).toLowerCase();return db.prepare("SELECT * FROM users WHERE active=1 AND directory_active=1 AND registration_state='active' AND account_kind='human' ORDER BY name").all().filter(x=>(x.name+' '+x.email+' '+x.username).toLowerCase().includes(q)&&(p.project_type!=='external'||projects.canPortal(x,p))).slice(0,50).map(x=>({id:x.id,name:x.name,email:x.email,username:x.username}));}
  function times(t){const total=Math.max(0,(t.closed_at?Date.parse(t.closed_at):t.status==='closed'?Date.parse(t.updated_at):t.archived_at?Date.parse(t.archived_at):clock())-Date.parse(t.created_at)),map=new Map();for(const s of db.prepare('SELECT * FROM status_spans WHERE ticket_id=? ORDER BY id').all(t.id)){const entry=map.get(s.status_key)||{key:s.status_key,name:s.status_name,total_ms:0};entry.total_ms+=Math.max(0,(s.ended_at?Date.parse(s.ended_at):t.closed_at?Date.parse(t.closed_at):t.archived_at?Date.parse(t.archived_at):clock())-Date.parse(s.started_at));map.set(s.status_key,entry);}return {total_ms:total,closed:Boolean(t.closed_at),history_complete:Boolean(t.tracking_complete),statuses:[...map.values()]};}
  function link(a,b,kind,u){const source=requireTicket(a,u),target=requireTicket(b,u);if(a===b)fail(400,'Nie można powiązać zgłoszenia z nim samym.');kind=choice(kind,['related','cloned','sync'],'Typ powiązania');const [lo,hi]=[source.id,target.id].sort((a,b)=>a-b);db.prepare('INSERT OR IGNORE INTO ticket_links(source_id,target_id,kind,created_by,created_at) VALUES(?,?,?,?,?)').run(lo,hi,kind,u.id,stamp());projects.audit(source.project_id,u,'ticket.linked',{source:lo,target:hi,kind});}
  function links(t,u){if(!projects.canWork(u,projects.project(t.project_id)))return [];return db.prepare('SELECT * FROM ticket_links WHERE source_id=? OR target_id=? ORDER BY id').all(t.id,t.id).map(l=>({link:l,t:ticket(l.source_id===t.id?l.target_id:l.source_id)})).filter(x=>x.t&&!x.t.deleted_at&&projects.canWork(u,projects.project(x.t.project_id))).map(x=>({id:x.link.id,kind:x.link.kind,key:x.t.key,title:x.t.title,status:x.t.status}));}
  function copy(t,p,u,b={}){
    if(t.deleted_at||t.archived_at||p.archived||p.module_type==='assets')fail(409,'Projekt docelowy nie przyjmuje zgłoszeń.');
    const r=b.request_type_id?db.prepare('SELECT * FROM request_types WHERE id=? AND project_id=? AND enabled=1').get(b.request_type_id,p.id):db.prepare('SELECT * FROM request_types WHERE project_id=? AND base_type=? AND enabled=1 ORDER BY id LIMIT 1').get(p.id,t.type);
    if(!r)fail(400,'Wybierz aktywny formularz docelowy.');
    const targetFields=JSON.parse(r.fields),oldValues=JSON.parse(t.custom_values||'{}'),values=b.custom_values??Object.fromEntries(targetFields.filter(f=>Object.hasOwn(oldValues,f.key)).map(f=>[f.key,oldValues[f.key]]));
    const f=catalog.prepare(p,{request_type_id:r.id,request_type_version:r.version,priority:t.priority,title:t.title,description:t.description,custom_values:values},false),initial=workflows.start(p),n=projects.project(p.id).next_number,key=projects.issueKey(p,n),s=stamp();if(n>2000000000)fail(409,'Wyczerpana numeracja.');
    db.prepare('UPDATE projects SET next_number=next_number+1,version=version+1 WHERE id=?').run(p.id);
    const reporterId=b.reporter_id??t.reporter_id;
    const id=Number(db.prepare('INSERT INTO tickets(project_id,key,number,title,description,type,priority,status,workflow_status,reporter_id,created_by,created_at,updated_at,request_type_id,form_snapshot,custom_values,origin) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(p.id,key,n,t.title,t.description,f.type,f.priority,initial.category,initial.key,reporterId,u.id,s,s,f.id,f.snapshot,f.values,b.origin||'clone').lastInsertRowid);
    db.prepare('INSERT INTO activity(ticket_id,actor_id,body,created_at) VALUES(?,?,?,?)').run(id,u.id,'Utworzono na podstawie '+t.key+'.',s);link(t.id,id,b.origin==='sync'?'sync':'cloned',u);workflows.run(ticket(id),'ticket_created',u);return ticket(id);
  }
  function clone(id,b,u){return tx(()=>{const t=requireTicket(id,u),p=projects.requireProject(b.project_id??t.project_id,u);reporter(p,b.reporter_id??t.reporter_id,u);return copy(t,p,u,b);});}
  function saveSettings(id,b,u){const p=projects.requireProject(id,u,true);if(p.archived)fail(409,'Projekt jest zarchiwizowany.');if(b.version!==p.version)fail(409,'Projekt zmienił się. Odśwież ustawienia.');const old=settings(p),w=workflows.get(id),keys=w.statuses.map(s=>s.key),out={...old};
    for(const k of ['resolution_required','time_tracking','portal_company_tickets'])if(b[k]!==undefined)out[k]=boolean(b[k],k);
    if(b.resolution_statuses!==undefined){if(!Array.isArray(b.resolution_statuses))fail(400,'Wybierz statusy rozwiązania.');out.resolution_statuses=b.resolution_statuses.map(v=>choice(v,keys,'Status rozwiązania'));}
    if(b.asset_projects!==undefined){if(!Array.isArray(b.asset_projects)||b.asset_projects.length>100)fail(400,'Lista projektów urządzeń jest nieprawidłowa.');out.asset_projects=b.asset_projects.map(v=>{integer(v,'Projekt urządzeń');const x=projects.project(v);if(!x||x.module_type!=='assets'||!projects.canWork(u,x))fail(400,'Brak dostępu do projektu urządzeń.');return v;});}
    if(b.sla!==undefined){out.sla=validateSlaConfig(b.sla,keys);for(const r of out.sla.rules)for(const id of r.request_type_ids)if(!db.prepare('SELECT id FROM request_types WHERE id=? AND project_id=?').get(id,p.id))fail(400,'Formularz SLA musi należeć do projektu.');}
    if(b.portal!==undefined){const a=b.portal;out.portal={welcome:text(a.welcome??'','Powitanie',0,3000),footer:text(a.footer??'','Stopka',0,1000),layout:choice(a.layout||'cards',['cards','list'],'Układ'),accent:choice(a.accent||'blue',['blue','teal','violet','orange'],'Kolor'),show_recent:boolean(a.show_recent??true,'Ostatnie zgłoszenia'),show_search:boolean(a.show_search??true,'Wyszukiwarka')};}
    return tx(()=>{db.prepare('UPDATE projects SET settings=?,version=version+1 WHERE id=?').run(JSON.stringify(out),id);projects.audit(id,u,'project.settings_updated',{keys:Object.keys(b).filter(k=>k!=='version')});return projects.view(projects.project(id),u);});
  }
  function detail(t,u){const staff=projects.canWork(u,projects.project(t.project_id));return {watching:staff&&Boolean(db.prepare('SELECT 1 FROM ticket_watchers WHERE ticket_id=? AND user_id=?').get(t.id,u.id)),watcher_count:staff?db.prepare('SELECT COUNT(*) n FROM ticket_watchers WHERE ticket_id=?').get(t.id).n:0,time:settings(projects.project(t.project_id)).time_tracking===false?null:times(t),sla:sla.metrics(t),links:links(t,u),assets:staff?db.prepare('SELECT a.id,a.asset_key,a.name,a.project_id FROM ticket_assets ta JOIN assets a ON a.id=ta.asset_id WHERE ta.ticket_id=?').all(t.id).filter(a=>projects.canWork(u,projects.project(a.project_id))):[]};}
  function commentExtras(c,t,u){const p=projects.project(t.project_id),staff=projects.canWork(u,p),refs=[];for(const m of c.body.matchAll(/\b[A-Z][A-Z0-9]{1,9}-[0-9]{1,10}\b/g)){const x=db.prepare('SELECT * FROM tickets WHERE key=? OR id=(SELECT ticket_id FROM ticket_aliases WHERE key=?)').get(m[0],m[0]);if(x&&projects.canRead(u,projects.project(x.project_id),x))refs.push({text:m[0],key:x.key});}const mentions=[];for(const m of c.body.matchAll(/@([a-zA-Z0-9._-]+)/g)){const x=db.prepare('SELECT * FROM users WHERE username=?').get(m[1]);if(x&&(staff||x.id===u.id||projects.canWork(x,p)))mentions.push({username:x.username,name:x.name,id:x.id});}return {...c,links:refs,mentions,avatar_url:'/api/avatars/'+c.author_id};}
  return {ticket,requireTicket,reporter,reporters,organization,times,link,links,copy,clone,saveSettings,detail,commentExtras,settings};
}
