import {raster} from './installation.mjs';
import {randomBytes,randomInt,createHash} from 'node:crypto';
import {now,fail,text,email,integer,choice,boolean,txFor} from './core.mjs';
import {username,parts} from './usernames.mjs';
const hash=s=>createHash('sha256').update(String(s)).digest('hex');
export function createIdentity(db,projects,accounts,{origin,encodePassword,clock=Date.now}){
  const tx=txFor(db),admin=u=>{if(u.role!=='admin')fail(403,'Wymagany administrator.');},local=u=>{if(u.auth_source==='ldap')fail(403,'Dane tożsamości tego konta są zarządzane przez LDAP.');};
  const names=b=>{const p=b.first_name!==undefined?{first_name:text(b.first_name,'Imię',1,60),last_name:text(b.last_name??'','Nazwisko',0,80)}:parts(text(b.name,'Imię i nazwisko',2,100));return {...p,name:(p.first_name+' '+p.last_name).trim()};};
  function assignName(id,b){const p=names(b),un=username(db,p.first_name,p.last_name,b.username,id);db.prepare('UPDATE users SET first_name=?,last_name=?,name=?,username=? WHERE id=?').run(p.first_name,p.last_name,p.name,un,id);return un;}
  async function create(b,u){admin(u);const p=names(b),kind=choice(b.account_kind||'human',['human','service'],'Typ konta'),role=kind==='service'?'agent':choice(b.role,['admin','agent','customer'],'Rola'),mail=email(b.email),un=username(db,p.first_name,p.last_name,b.username),invite=kind==='human'&&!b.password;
    if(invite&&!accounts.settings().smtp_configured)fail(400,'Zaproszenie wymaga skonfigurowanej poczty SMTP.');const encoded=kind==='service'?'!service':invite?'!invited':await encodePassword(b.password);
    return tx(()=>{const current=db.prepare('SELECT * FROM users WHERE id=?').get(u.id);if(!current?.active||current.role!=='admin'||current.version!==u.version)fail(403,'Uprawnienia administratora zmieniły się.');if(db.prepare('SELECT id FROM users WHERE email=? OR username=?').get(mail,un))fail(409,'Adres lub nazwa konta są już zajęte.');const id=Number(db.prepare('INSERT INTO users(email,name,first_name,last_name,username,password,role,account_kind,must_change,registration_state,is_internal,created_at) VALUES(?,?,?,?,?,?,?,?,0,?,?,?)').run(mail,p.name,p.first_name,p.last_name,un,encoded,role,kind,invite?'pending_email':'active',Number(boolean(b.is_internal??role!=='customer','Konto firmowe')),now()).lastInsertRowid);if(invite){const token=randomBytes(32).toString('hex');db.prepare('INSERT INTO identity_tokens(token,user_id,purpose,payload,expires_at) VALUES(?,?,\'invite\',\'{}\',?)').run(hash(token),id,clock()+48*3600000);accounts.queue(mail,'Zaproszenie do '+accounts.settings().brand_name,`Dzień dobry ${p.first_name},\n\nUtworzono dla Ciebie konto ${un}. Potwierdź adres i ustaw hasło:\n${origin}/#/invite/${token}\n\nLink jest ważny 48 godzin.`);}projects.audit(null,u,'user.created',{user_id:id,role,account_kind:kind,invited:invite});return db.prepare('SELECT * FROM users WHERE id=?').get(id);});
  }
  async function acceptInvite(raw,password){if(typeof raw!=='string'||!/^[a-f0-9]{64}$/.test(raw))fail(400,'Zaproszenie jest nieprawidłowe.');const encoded=await encodePassword(password);return tx(()=>{const r=db.prepare("SELECT a.*,u.active,u.account_kind,u.registration_state FROM identity_tokens a JOIN users u ON u.id=a.user_id WHERE a.token=? AND a.purpose='invite' AND a.expires_at>?").get(hash(raw),clock());if(!r||!r.active||r.account_kind!=='human'||r.registration_state!=='pending_email')fail(400,'Zaproszenie wygasło lub zostało wykorzystane.');db.prepare("UPDATE users SET password=?,registration_state='active',email_verified=1,must_change=0,version=version+1 WHERE id=?").run(encoded,r.user_id);db.prepare('DELETE FROM identity_tokens WHERE user_id=?').run(r.user_id);projects.audit(null,{id:r.user_id},'invitation.accepted',{});return {message:'Konto aktywne. Możesz się zalogować.'};});}
  function request(u,b){local(u);const kind=choice(b.kind,['name','email'],'Zmiana profilu');let payload;
    if(kind==='name')payload={...names(b),before:{first_name:u.first_name,last_name:u.last_name}};
    else {const value=email(b.email);if(value===u.email)fail(400,'Podaj inny adres.');payload={email:value,old_email:u.email,note:text(b.note,'Uzasadnienie braku dostępu',5,2000)};}
    return tx(()=>{if(db.prepare("SELECT id FROM profile_requests WHERE user_id=? AND kind=? AND state='pending'").get(u.id,kind))fail(409,'Masz już oczekującą zmianę tego typu.');const id=Number(db.prepare('INSERT INTO profile_requests(user_id,kind,payload,created_at) VALUES(?,?,?,?)').run(u.id,kind,JSON.stringify(payload),now()).lastInsertRowid);for(const a of db.prepare("SELECT id FROM users WHERE role='admin' AND active=1").all())db.prepare('INSERT INTO notifications(user_id,body,created_at) VALUES(?,?,?)').run(a.id,'Prośba o zatwierdzenie zmiany profilu: '+u.name,now());projects.audit(null,u,'profile.requested',{request_id:id,kind});return {id,message:'Zmiana czeka na zatwierdzenie administratora.'};});
  }
  function requests(u){return db.prepare(`SELECT r.*,u.name,u.email FROM profile_requests r JOIN users u ON u.id=r.user_id ${u.role==='admin'?'':'WHERE r.user_id=?'} ORDER BY r.id DESC LIMIT 200`).all(...(u.role==='admin'?[]:[u.id])).map(r=>({...r,payload:JSON.parse(r.payload)}));}
  function review(id,b,u){admin(u);return tx(()=>{const r=db.prepare("SELECT * FROM profile_requests WHERE id=? AND state='pending'").get(integer(id,'Wniosek'));if(!r)fail(409,'Wniosek już rozpatrzono.');const target=db.prepare('SELECT * FROM users WHERE id=?').get(r.user_id),p=JSON.parse(r.payload);local(target);const approved=boolean(b.approve,'Decyzja');
      if(approved){if(r.kind==='name'){if(target.first_name!==p.before.first_name||target.last_name!==p.before.last_name)fail(409,'Profil zmienił się od złożenia wniosku.');db.prepare('UPDATE users SET first_name=?,last_name=?,name=?,version=version+1 WHERE id=?').run(p.first_name,p.last_name,p.name,target.id);}else{if(target.email!==p.old_email)fail(409,'Adres zmienił się od złożenia wniosku.');setEmail(target,p.email,false);}}
      db.prepare('UPDATE profile_requests SET state=?,reviewer_id=?,reviewed_at=? WHERE id=?').run(approved?'approved':'rejected',u.id,now(),r.id);projects.audit(null,u,'profile.reviewed',{request_id:r.id,approved,user_id:target.id});db.prepare('INSERT INTO notifications(user_id,body,created_at) VALUES(?,?,?)').run(target.id,approved?'Administrator zatwierdził zmianę profilu.':'Administrator odrzucił zmianę profilu.',now());return {ok:true};});
  }
  function setEmail(u,value,verified){if(db.prepare('SELECT id FROM users WHERE email=? AND id<>?').get(value,u.id))fail(409,'Adres jest już zajęty.');db.prepare('UPDATE users SET email=?,email_verified=?,version=version+1 WHERE id=?').run(value,Number(verified),u.id);db.prepare('DELETE FROM sessions WHERE user_id=?').run(u.id);db.prepare('DELETE FROM account_tokens WHERE user_id=?').run(u.id);db.prepare("DELETE FROM identity_tokens WHERE user_id=? AND purpose='email_change'").run(u.id);}
  function emailBegin(u,b){local(u);const value=email(b.email);if(value===u.email)fail(400,'Podaj inny adres.');if(!accounts.settings().smtp_configured)fail(503,'Zmiana adresu wymaga poczty SMTP.');if(db.prepare('SELECT id FROM users WHERE email=?').get(value))fail(409,'Adres jest już zajęty.');const raw=randomBytes(32).toString('hex'),code=String(randomInt(100000,1000000));return tx(()=>{db.prepare("DELETE FROM identity_tokens WHERE user_id=? AND purpose='email_change'").run(u.id);db.prepare("INSERT INTO identity_tokens(token,user_id,purpose,payload,expires_at) VALUES(?,?,'email_change',?,?)").run(hash(raw),u.id,JSON.stringify({old:u.email,next:value,step:'old',code:hash(raw+code)}),clock()+10*60000);accounts.queue(u.email,'Potwierdzenie zmiany adresu',`Kod potwierdzający dostęp do obecnego adresu: ${code}\n\nKod jest ważny 10 minut. Jeśli nie zmieniasz adresu w systemie zgłoszeń, zignoruj tę wiadomość.`);return {token:raw,step:'old',message:'Kod wysłany na dotychczasowy adres.'};});}
  function emailVerify(u,b){local(u);const raw=text(b.token,'Token',64,64),code=text(b.code,'Kod',6,6),r=db.prepare("SELECT * FROM identity_tokens WHERE token=? AND user_id=? AND purpose='email_change' AND expires_at>?").get(hash(raw),u.id,clock());if(!r||r.attempts>=5)fail(400,'Kod wygasł lub przekroczono liczbę prób.');const p=JSON.parse(r.payload);if(u.email!==p.old)fail(409,'Adres konta zmienił się. Rozpocznij od nowa.');db.prepare('UPDATE identity_tokens SET attempts=attempts+1 WHERE token=?').run(r.token);if(p.code!==hash(raw+code))fail(400,'Nieprawidłowy kod.');return tx(()=>{if(p.step==='old'){const next=String(randomInt(100000,1000000));db.prepare('UPDATE identity_tokens SET payload=?,expires_at=?,attempts=0 WHERE token=?').run(JSON.stringify({...p,step:'new',code:hash(raw+next)}),clock()+10*60000,r.token);accounts.queue(p.next,'Potwierdź nowy adres',`Kod potwierdzający nowy adres e-mail: ${next}\n\nKod jest ważny 10 minut.`);return {token:raw,step:'new',message:'Teraz wpisz kod z nowego adresu.'};}setEmail(u,p.next,true);projects.audit(null,u,'profile.email_verified',{previous:p.old,current:p.next});return {step:'done',message:'Adres zmieniony. Zaloguj się ponownie.'};});}
  function avatar(u,b){if(b.remove===true){db.prepare('DELETE FROM avatars WHERE user_id=?').run(u.id);return {ok:true};}const {mime,body:data}=raster(b.data);db.prepare('INSERT INTO avatars(user_id,mime,body,updated_at) VALUES(?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET mime=excluded.mime,body=excluded.body,updated_at=excluded.updated_at').run(u.id,mime,data,now());return {ok:true};}
  function theme(u,b){const value=choice(b.theme,['light','dark','system'],'Motyw');db.prepare('UPDATE users SET theme=? WHERE id=?').run(value,u.id);return {theme:value};}
  return {create,assignName,acceptInvite,request,requests,review,emailBegin,emailVerify,avatar,theme};
}
