import {renderMail} from './mail-templates.mjs';
import {mailAllowed} from './mail-access.mjs';
import {maintenance} from './maintenance.mjs';
import nodemailer from 'nodemailer';
import {createNotifications} from './notifications.mjs';
import {ImapFlow} from 'imapflow';
import {simpleParser} from 'mailparser';
import {randomBytes,createHash} from 'node:crypto';
import {fail,now,text,email,integer,boolean,txFor} from './core.mjs';
import {secretStore} from './secrets.mjs';
import {username,parts} from './usernames.mjs';
import {emailHtml,replyLine} from './mail-template.mjs';
export function stripReply(value){return String(value||'').split(new RegExp(`(?:^|\n)\\s*(?:>\\s*)?(?:${replyLine}|_{10,})`,'i'))[0].split(/\n(?:On .+wrote:|W dniu .+napisał(?:a)?:|Od: .+\nWysłano:)/i)[0].replace(/\n>[^\n]*/g,'').trim();}
export function createMail(db,projects,catalog,workflows,desk,accounts,{origin,dataDir,clock=Date.now,imapFactory=c=>new ImapFlow(c),transportFactory=c=>nodemailer.createTransport(c)}){
  const tx=txFor(db),secrets=secretStore(dataDir),notifications=createNotifications(db,projects,desk);let polling=false,sending=false,timer,stopping=false;const connections=new Set();
  const row=id=>db.prepare('SELECT * FROM email_channels WHERE id=?').get(id),config=r=>({...JSON.parse(r.config),...JSON.parse(secrets.open(r.secret))});
  const output=r=>{const {secret,...out}=r;return {...out,config:JSON.parse(r.config),has_secret:Boolean(secret),enabled:Boolean(r.enabled)};};
  function list(u){if(u.role!=='admin')fail(403,'Kanały pocztowe ustawia administrator.');return db.prepare('SELECT * FROM email_channels ORDER BY name').all().map(output);}
  function save(id,b,u){if(u.role!=='admin')fail(403,'Wymagany administrator.');const old=id?row(id):null;if(id&&(!old||old.version!==b.version))fail(409,'Kanał poczty zmienił się.');const p=projects.requireProject(integer(b.project_id,'Projekt'),u,true);if(p.module_type==='assets')fail(400,'Poczta wymaga projektu zgłoszeń.');if(old&&old.project_id!==p.id)fail(400,'Dla innego projektu utwórz nowy kanał.');const c=b.config||{};
    const mode='custom',imapEnabled=boolean(c.imap_enabled??true,'Odbiór IMAP');
    const cfg={smtp_mode:mode,imap_enabled:imapEnabled,imap_host:text(c.imap_host||'','Serwer IMAP',imapEnabled?1:0,253),imap_port:integer(c.imap_port??993,'Port IMAP',1,65535),imap_secure:boolean(c.imap_secure??true,'IMAP TLS'),imap_user:text(c.imap_user||'','Login IMAP',imapEnabled?1:0,300),folder:text(c.folder||'INBOX','Folder IMAP',1,100),smtp_host:text(c.smtp_host||'','Serwer SMTP',mode==='custom'?1:0,253),smtp_port:integer(c.smtp_port??587,'Port SMTP',1,65535),smtp_secure:boolean(c.smtp_secure??false,'SMTP TLS'),smtp_user:text(c.smtp_user||'','Login SMTP',0,300),request_type_id:integer(c.request_type_id,'Formularz email'),allow_new_senders:boolean(c.allow_new_senders??true,'Nowi nadawcy'),allowed_domains:(c.allowed_domains||[]).map(d=>email('user@'+d).split('@')[1]),start_from_now:boolean(c.start_from_now??true,'Od nowych wiadomości')};
    if(!db.prepare('SELECT id FROM request_types WHERE id=? AND project_id=? AND enabled=1').get(cfg.request_type_id,p.id))fail(400,'Wybierz aktywny formularz projektu.');for(const host of [cfg.imap_host,cfg.smtp_host])if(/[\s/:@]/.test(host))fail(400,'Podaj nazwę serwera bez protokołu, portu i danych logowania.');
    const oldSecret=old?JSON.parse(secrets.open(old.secret)):{};const secret={imap_pass:c.imap_pass?text(c.imap_pass,'Hasło IMAP',1,4000):oldSecret.imap_pass,smtp_pass:c.smtp_pass?text(c.smtp_pass,'Hasło SMTP',1,4000):oldSecret.smtp_pass};if((imapEnabled&&!secret.imap_pass)||(mode==='custom'&&cfg.smtp_user&&!secret.smtp_pass))fail(400,'Uzupełnij wymagane hasło IMAP lub osobnego SMTP.');
    const reset=old&&['imap_host','imap_port','imap_user','folder'].some(k=>JSON.parse(old.config)[k]!==cfg[k]);return tx(()=>{const values=[p.id,text(b.name,'Nazwa zespołu',2,100),email(b.email),JSON.stringify(cfg),secrets.seal(JSON.stringify(secret)),Number(boolean(b.enabled??false,'Kanał aktywny'))];if(old)db.prepare('UPDATE email_channels SET project_id=?,name=?,email=?,config=?,secret=?,enabled=?,version=version+1,uidvalidity=CASE WHEN ? THEN NULL ELSE uidvalidity END,uid_cursor=CASE WHEN ? THEN 0 ELSE uid_cursor END WHERE id=?').run(...values,Number(Boolean(reset)),Number(Boolean(reset)),id);else id=Number(db.prepare('INSERT INTO email_channels(project_id,name,email,config,secret,enabled) VALUES(?,?,?,?,?,?)').run(...values).lastInsertRowid);db.prepare("UPDATE mail_outbox SET channel_id=? WHERE channel_id IS NULL AND status='queued' AND ticket_id IN (SELECT id FROM tickets WHERE project_id=?)").run(id,p.id);projects.audit(p.id,u,'mail.configured',{channel_id:id});return output(row(id));});
  }
  function enqueue(channel,to,subject,body,ticketId=null,internal=false){
    if(String(to||'').toLowerCase().endsWith('.invalid'))return;
    const messageId='<'+randomBytes(24).toString('hex')+'@'+new URL(origin).hostname+'>';let prior;
    if(ticketId){prior=db.prepare('SELECT message_id FROM mail_threads WHERE ticket_id=? ORDER BY rowid DESC LIMIT 1').get(ticketId)?.message_id;db.prepare('INSERT INTO mail_threads(message_id,ticket_id,channel_id) VALUES(?,?,?)').run(messageId,ticketId,channel?.id??null);}
    const metadata={desk_internal:internal,messageId,...(prior?{inReplyTo:prior,references:[prior]}:{}),...(channel?{replyTo:{name:channel.name,address:channel.email}}:{}),headers:{'Auto-Submitted':'auto-generated','X-Auto-Response-Suppress':'All'}};
    db.prepare('INSERT INTO mail_outbox(recipient,subject,body,next_attempt,created_at,channel_id,ticket_id,metadata) VALUES(?,?,?,?,?,?,?,?)').run(to,subject,secrets.seal(body),clock(),now(),channel?.id??null,ticketId,secrets.seal(JSON.stringify(metadata)));
  }
  function notify(event){
    const t=desk.ticket(event.ticket_id);if(!t||t.deleted_at)return;
    const p=projects.project(t.project_id),payload=JSON.parse(event.payload);let body,actorId=null,internal=false,mentions=[],staffUpdate=['sync','automation'].includes(payload.origin);
    actorId=event.event==='ticket_created'?t.created_by:payload.actor_id??t.last_actor_id;
    if(event.event==='comment_added'){const c=db.prepare('SELECT * FROM comments WHERE id=?').get(payload.comment_id);if(!c)return;internal=Boolean(c.internal);staffUpdate=['sync','automation'].includes(c.origin);body=(internal?'Notatka wewnętrzna:\n\n':'')+c.body;actorId=c.actual_actor_id||c.author_id;mentions=[...c.body.matchAll(/@([a-zA-Z0-9._-]+)/g)].map(m=>db.prepare('SELECT id FROM users WHERE username=?').get(m[1])?.id).filter(Boolean);}
    else if(event.event==='ticket_created')body='Otrzymaliśmy zgłoszenie. Zespół zajmie się Twoją sprawą.\n\n'+t.description;
    else if(event.event==='status_changed')body='Status zgłoszenia został zmieniony na: '+(workflows.get(p.id).statuses.find(s=>s.key===payload.to)?.name||payload.to)+(t.resolution_text?'\n\nRozwiązanie:\n'+t.resolution_text:'');
    else if(event.event==='ticket_updated'){body='Zaktualizowano zgłoszenie. Aktualne szczegóły znajdziesz w systemie.';actorId=payload.actor_id;}else return;
    const channel=t.mail_channel_id?row(t.mail_channel_id):db.prepare('SELECT * FROM email_channels WHERE project_id=? ORDER BY enabled DESC,id LIMIT 1').get(p.id);
    const recipients=notifications.recipients(t,{actor_id:actorId,internal,mentions,staff_update:staffUpdate});
    // A submitted request receives a receipt even when submitted by its reporter.
    if(event.event==='ticket_created'){const reporter=db.prepare('SELECT * FROM users WHERE id=?').get(t.reporter_id);if(reporter?.active&&projects.canRead(reporter,p,t)&&!recipients.some(u=>u.id===reporter.id))recipients.push(reporter);const settings=JSON.parse(p.settings||'{}');for(const u of team(t,settings.notify_new_team?'team':settings.notify_new_managers?'managers':'none'))if(u.id!==actorId&&!recipients.some(x=>x.id===u.id))recipients.push(u);}
    let templates=db.prepare('SELECT * FROM mail_templates WHERE enabled=1 AND event=? AND (project_id IS NULL OR project_id=?) ORDER BY id').all(event.event,p.id);
    if(templates.some(x=>x.project_id===p.id&&x.audience==='participants'))templates=templates.filter(x=>x.project_id||x.audience!=='participants');
    const primary=templates.filter(x=>x.audience==='participants');
    if(!primary.length)for(const u of recipients)enqueue(channel,u.email,`[${t.key}] ${t.title}`,replyLine+'\n___________________________________\n\n'+body+'\n\n'+origin+'/#/ticket/'+t.key,t.id,internal);
    for(const template of templates)sendTemplate(template,t,{actorId,internal,update:body,recipients,receipt:event.event==='ticket_created'});
  }
  function team(t,audience){if(!['team','managers'].includes(audience))return [];const p=projects.project(t.project_id);return db.prepare("SELECT DISTINCT u.* FROM project_members m JOIN users u ON u.id=m.user_id WHERE m.project_id=? AND m.role IN ('agent','manager')").all(p.id).filter(u=>u.active&&u.directory_active&&u.registration_state==='active'&&projects.canWork(u,p)&&(audience==='team'||projects.canManage(u,p)));}
  function sendTemplate(template,t,{actorId=null,internal=false,update='',recipients,receipt=false}={}){const p=projects.project(t.project_id);if(!template.enabled||(template.project_id&&template.project_id!==p.id))fail(409,'Szablon poczty jest niedostępny dla projektu.');const staffOnly=internal||['team','managers'].includes(template.audience);let users=template.audience==='participants'?(recipients||notifications.recipients(t,{actor_id:actorId,internal})):template.audience==='reporter'?[db.prepare('SELECT * FROM users WHERE id=?').get(t.reporter_id)]:template.audience==='watchers'?db.prepare('SELECT u.* FROM ticket_watchers w JOIN users u ON u.id=w.user_id WHERE w.ticket_id=?').all(t.id):team(t,template.audience);users=users.filter(u=>u&&(u.id!==actorId||(receipt&&u.id===t.reporter_id))&&u.active&&u.directory_active&&u.registration_state==='active'&&projects.canRead(u,p,t)&&(!staffOnly||projects.canWork(u,p)));const channel=t.mail_channel_id?row(t.mail_channel_id):db.prepare('SELECT * FROM email_channels WHERE project_id=? ORDER BY enabled DESC,id LIMIT 1').get(p.id),values={key:t.key,title:t.title,description:t.description,update,status:workflows.get(p.id).statuses.find(s=>s.key===t.workflow_status)?.name||t.status,url:origin+'/#/ticket/'+t.key,reporter:db.prepare('SELECT name FROM users WHERE id=?').get(t.reporter_id)?.name,project:p.name};for(const u of users)enqueue(channel,u.email,renderMail(template.subject,values).replace(/[\r\n]/g,' ').slice(0,250),replyLine+'\n___________________________________\n\n'+renderMail(template.body,values),t.id,staffOnly);}
  function automationEmail(id,t,event,actorId){const template=db.prepare('SELECT * FROM mail_templates WHERE id=?').get(id);if(!template)fail(409,'Szablon e-mail nie istnieje.');sendTemplate(template,t,{actorId,update:'Aktualizacja z automatyzacji: '+event});}
  async function ingest(channelId,validity,uid,source){
    const channel=row(channelId);if(!channel?.enabled)return;const cfg=config(channel);if(db.prepare('SELECT id FROM mail_receipts WHERE channel_id=? AND uidvalidity=? AND uid=?').get(channel.id,String(validity),uid))return;
    let message;try{message=await simpleParser(source,{skipHtmlToText:false,skipTextToHtml:true,maxHtmlLengthToParse:1000000});}catch{message=null;}
    return tx(()=>{
      let result={status:'ignored',detail:'Nieprawidłowa wiadomość.',ticket_id:null};const receipt=()=>{db.prepare('INSERT INTO mail_receipts(channel_id,uidvalidity,uid,message_id,ticket_id,status,detail,created_at) VALUES(?,?,?,?,?,?,?,?)').run(channel.id,String(validity),uid,message?.messageId||null,result.ticket_id,result.status,result.detail,now());return result;};
      if(!message)return receipt();const from=message.from?.value||[],auto=String(message.headers.get('auto-submitted')||'no').toLowerCase();
      if(from.length!==1||auto!=='no'||/^(bulk|junk|list)$/i.test(String(message.headers.get('precedence')||''))||message.headers.has('list-id')){result.detail='Pominięto automatyczną lub listową wiadomość.';return receipt();}
      if(message.messageId&&db.prepare('SELECT id FROM mail_receipts WHERE channel_id=? AND message_id=?').get(channel.id,message.messageId)){result.detail='Wiadomość została już przetworzona.';return receipt();}
      const sender=String(from[0].address||'').toLowerCase();if(!sender||db.prepare('SELECT id FROM email_channels WHERE email=?').get(sender)){result.detail='Pominięto nadawcę będącego kanałem systemu.';return receipt();}
      let user=db.prepare('SELECT * FROM users WHERE email=?').get(sender);const p=projects.project(channel.project_id);if(p.archived){result.detail='Projekt jest zarchiwizowany.';return receipt();}
      const refs=[message.inReplyTo,...(Array.isArray(message.references)?message.references:message.references?[message.references]:[])].filter(Boolean);let t;
      for(const ref of refs){const found=db.prepare('SELECT t.* FROM mail_threads m JOIN tickets t ON t.id=m.ticket_id WHERE m.message_id=? AND t.project_id=?').get(ref,p.id);if(found){t=found;break;}}
      if(!t){const key=message.subject?.match(/\[([A-Z][A-Z0-9]{1,9}-\d{1,10})\]/)?.[1];if(key)t=db.prepare('SELECT * FROM tickets WHERE key=? AND project_id=?').get(key,p.id);}
      // An unknown sender must never gain access to an existing thread through its subject.
      if(!user&&cfg.allow_new_senders&&!t&&p.project_type==='external'&&p.portal_access!=='internal'&&(!cfg.allowed_domains.length||cfg.allowed_domains.includes(sender.split('@')[1]))){
        const n=parts((from[0].name||sender.split('@')[0]).slice(0,100)),un=username(db,n.first_name,n.last_name),id=Number(db.prepare("INSERT INTO users(email,name,first_name,last_name,username,password,role,must_change,registration_state,created_at) VALUES(?,?,?,?,?,'!invited','customer',0,'pending_email',?)").run(email(sender),(n.first_name+' '+n.last_name).trim(),n.first_name,n.last_name,un,now()).lastInsertRowid);
        db.prepare("INSERT OR IGNORE INTO project_members(project_id,user_id,role) VALUES(?,?,'requester')").run(p.id,id);const token=randomBytes(32).toString('hex');db.prepare("INSERT INTO identity_tokens VALUES(?,?,'invite','{}',?,0)").run(createHash('sha256').update(token).digest('hex'),id,clock()+48*3600000);enqueue(channel,sender,'Potwierdź konto w '+accounts.settings().brand_name,'Aby otworzyć portal, potwierdź adres i ustaw hasło:\n'+origin+'/#/invite/'+token);user=db.prepare('SELECT * FROM users WHERE id=?').get(id);
      }
      if(!user?.active||!user.directory_active||user.account_kind==='service'||user.registration_state==='pending_approval'){result.detail='Nadawca nie ma aktywnego dostępu.';return receipt();}
      const body=stripReply(message.text||'').slice(0,20000);if(!body){result.detail='Brak treści odpowiedzi.';return receipt();}
      if(t){if(t.deleted_at||t.archived_at){result.detail='Sprawa usunięta lub zarchiwizowana.';return receipt();}if(!projects.canRead(user,p,t)){result.detail='Nadawca nie ma dostępu do sprawy.';return receipt();}if(t.status==='closed'||(!projects.canWork(user,p)&&t.customer_reply_locked)){result.detail='Zamknięta sprawa nie przyjmuje odpowiedzi.';enqueue(channel,sender,`[${t.key}] Sprawa jest zamknięta`,'Ta sprawa jest ostatecznie zamknięta. Wyślij nową wiadomość bez numeru starej sprawy lub utwórz nowe zgłoszenie w portalu.',t.id);return receipt();}
        db.prepare("INSERT INTO comments(ticket_id,author_id,actual_actor_id,body,internal,created_at,origin) VALUES(?,?,?,?,0,?,'email')").run(t.id,user.id,user.id,body,now());db.prepare('UPDATE tickets SET updated_at=?,version=version+1,first_response_at=CASE WHEN ? THEN COALESCE(first_response_at,?) ELSE first_response_at END WHERE id=?').run(now(),Number(projects.canWork(user,p)&&user.id!==t.reporter_id),now(),t.id);workflows.run(t,projects.canWork(user,p)?'agent_reply':'customer_reply',user);
      }else{
        if(!projects.canPortal(user,p)&&!projects.canWork(user,p)){result.detail='Nadawca nie ma dostępu do projektu.';return receipt();}
        const r=db.prepare('SELECT * FROM request_types WHERE id=? AND project_id=? AND enabled=1').get(cfg.request_type_id,p.id);if(!r){result.detail='Formularz kanału jest niedostępny.';return receipt();}
        let f;try{f=catalog.prepare(p,{request_type_id:r.id,request_type_version:r.version,title:message.subject||'Zgłoszenie e-mail',description:body},!projects.canWork(user,p));}catch(e){result.detail=e.status?e.message:'Nie można wypełnić formularza kanału.';return receipt();}
        const n=projects.project(p.id).next_number;if(n>2000000000)fail(409,'Wyczerpana numeracja.');const key=projects.issueKey(p,n),initial=workflows.start(p),date=now();db.prepare('UPDATE projects SET next_number=next_number+1,version=version+1 WHERE id=?').run(p.id);
        const id=Number(db.prepare("INSERT INTO tickets(project_id,key,number,title,description,type,priority,status,workflow_status,reporter_id,created_by,created_at,updated_at,request_type_id,form_snapshot,custom_values,origin,mail_channel_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,'email',?)").run(p.id,key,n,text(f.title,'Temat',3,200),text(f.description,'Opis',3,20000),f.type,f.priority,initial.category,initial.key,user.id,user.id,date,date,f.id,f.snapshot,f.values,channel.id).lastInsertRowid);t=desk.ticket(id);projects.audit(p.id,user,'ticket.email_created',{ticket_id:id,channel_id:channel.id});workflows.run(t,'ticket_created',user);
      }
      if(message.messageId)db.prepare('INSERT OR IGNORE INTO mail_threads VALUES(?,?,?)').run(message.messageId,t.id,channel.id);result={status:'processed',ticket_id:t.id,detail:message.attachments?.length?'Przetworzono tekst; wiadomość zawiera załączniki, które pozostają w skrzynce IMAP.':'Przetworzono.'};return receipt();
    });
  }
  async function poll(){if(maintenance())return;if(polling||stopping)return;polling=true;try{for(const channel of db.prepare('SELECT * FROM email_channels WHERE enabled=1 ORDER BY id').all()){
    const c=config(channel);if(c.imap_enabled===false)continue;const client=imapFactory({host:c.imap_host,port:c.imap_port,secure:c.imap_secure,doSTARTTLS:!c.imap_secure,auth:{user:c.imap_user,pass:c.imap_pass},tls:{minVersion:'TLSv1.2',rejectUnauthorized:true},logger:false,connectionTimeout:10000,greetingTimeout:10000,socketTimeout:30000});connections.add(client);try{await client.connect();const lock=await client.getMailboxLock(c.folder);try{
      const validity=String(client.mailbox.uidValidity),next=Number(client.mailbox.uidNext||1);let cursor=channel.uid_cursor;
      if(channel.uidvalidity!==validity){cursor=channel.uidvalidity===null&&c.start_from_now?Math.max(0,next-1):0;db.prepare('UPDATE email_channels SET uidvalidity=?,uid_cursor=? WHERE id=?').run(validity,cursor,channel.id);}
      if(next>cursor+1){const batch=await client.fetchAll(`${cursor+1}:${Math.min(next-1,cursor+100)}`,{uid:true,size:true},{uid:true});for(const m of batch){if(m.uid<=cursor)continue;if(m.size<=2*1024*1024){const data=await client.fetchOne(m.uid,{source:true},{uid:true});if(!data?.source)throw new Error('IMAP_SOURCE_UNAVAILABLE');await ingest(channel.id,validity,m.uid,data.source);}else db.prepare('INSERT OR IGNORE INTO mail_receipts(channel_id,uidvalidity,uid,status,detail,created_at) VALUES(?,?,?,\'ignored\',\'Wiadomość przekracza 2 MB; pozostaje w skrzynce.\',?)').run(channel.id,validity,m.uid,now());cursor=m.uid;db.prepare('UPDATE email_channels SET uid_cursor=? WHERE id=?').run(cursor,channel.id);}if(!batch.length)db.prepare('UPDATE email_channels SET uid_cursor=? WHERE id=?').run(Math.min(next-1,cursor+100),channel.id);}
      db.prepare('UPDATE email_channels SET last_poll=?,last_error=NULL WHERE id=?').run(now(),channel.id);
    }finally{lock.release();}}catch(e){db.prepare('UPDATE email_channels SET last_poll=?,last_error=? WHERE id=?').run(now(),String(e.code||'IMAP_FAILED').slice(0,100),channel.id);}finally{await client.logout().catch(()=>{});connections.delete(client);}
  }}finally{polling=false;}}
  async function flush(){if(maintenance())return;if(sending||stopping)return;sending=true;try{for(const m of db.prepare("SELECT * FROM mail_outbox WHERE channel_id IS NOT NULL AND status='queued' AND next_attempt<=? ORDER BY id LIMIT 20").all(clock())){const metadata=m.metadata?JSON.parse(secrets.open(m.metadata)):{};if(!mailAllowed(db,m,metadata)){db.prepare("UPDATE mail_outbox SET status='failed',body='',metadata=NULL,last_error='Odbiorca utracił dostęp.' WHERE id=?").run(m.id);continue;}delete metadata.desk_internal;const ch=row(m.channel_id);if(!ch?.enabled)continue;const c=config(ch);if(c.smtp_mode==='default'||!c.smtp_host){db.prepare("UPDATE mail_outbox SET last_error='Uzupełnij własne SMTP zespołu.' WHERE id=?").run(m.id);continue;}const transport=transportFactory({host:c.smtp_host,port:c.smtp_port,secure:c.smtp_secure,requireTLS:!c.smtp_secure,...(c.smtp_user?{auth:{user:c.smtp_user,pass:c.smtp_pass}}:{}),tls:{minVersion:'TLSv1.2',rejectUnauthorized:true},connectionTimeout:8000,greetingTimeout:8000,socketTimeout:15000,dnsTimeout:5000,disableFileAccess:true,disableUrlAccess:true});try{const body=secrets.open(m.body),t=m.ticket_id?desk.ticket(m.ticket_id):null;await transport.sendMail({from:{name:ch.name,address:ch.email},to:{address:m.recipient},subject:m.subject,text:body,html:emailHtml({brand:accounts.settings().brand_name,title:m.subject,body,url:t?origin+'/#/ticket/'+t.key:origin,key:t?.key}),...metadata,replyTo:{name:ch.name,address:ch.email},disableFileAccess:true,disableUrlAccess:true});db.prepare("UPDATE mail_outbox SET status='sent',body='',metadata=NULL,attempts=attempts+1,last_error=NULL WHERE id=?").run(m.id);}catch(e){const n=m.attempts+1;db.prepare('UPDATE mail_outbox SET status=?,attempts=?,next_attempt=?,last_error=? WHERE id=?').run(n>=5?'failed':'queued',n,clock()+Math.min(30,2**n)*60000,String(e.code||'SMTP_FAILED').slice(0,80),m.id);}finally{transport.close?.();}}}finally{sending=false;}}
  const receipts=u=>{list(u);return db.prepare('SELECT r.*,c.name channel_name FROM mail_receipts r JOIN email_channels c ON c.id=r.channel_id ORDER BY r.id DESC LIMIT 100').all();};
  return {list,save,notify,enqueue,automationEmail,ingest,poll,flush,receipts,start(){timer=setInterval(()=>{void poll();void flush();},15000).unref();},stop(){stopping=true;clearInterval(timer);for(const c of connections)c.close();}};
}
