import {now,fail,text,integer,boolean,txFor} from './core.mjs';
export function createResources(db,projects,desk,workflows){
  const tx=txFor(db),admin=u=>{if(u.role!=='admin')fail(403,'Wymagany administrator.');};
  function organizations(u){if(!['admin','agent'].includes(u.role))return db.prepare('SELECT o.id,o.name,o.share_tickets FROM organizations o JOIN organization_members m ON m.organization_id=o.id WHERE m.user_id=?').all(u.id).map(o=>({...o,members:[u.id],projects:db.prepare('SELECT project_id FROM project_organizations WHERE organization_id=?').all(o.id).map(x=>x.project_id)}));return db.prepare('SELECT * FROM organizations ORDER BY name').all().filter(o=>u.role==='admin'||db.prepare('SELECT project_id FROM project_organizations WHERE organization_id=?').all(o.id).some(p=>projects.canWork(u,projects.project(p.project_id)))).map(o=>({...o,members:db.prepare('SELECT user_id FROM organization_members WHERE organization_id=?').all(o.id).map(x=>x.user_id),projects:db.prepare('SELECT project_id FROM project_organizations WHERE organization_id=?').all(o.id).map(x=>x.project_id)}));}
  function saveOrganization(id,b,u){admin(u);const old=id?db.prepare('SELECT * FROM organizations WHERE id=?').get(id):null;if(id&&(!old||old.version!==b.version))fail(409,'Organizacja zmieniła się.');const name=text(b.name,'Nazwa firmy lub grupy',2,100),share=Number(boolean(b.share_tickets??false,'Wspólne zgłoszenia'));
    if(!Array.isArray(b.members)||b.members.length>10000||!Array.isArray(b.projects)||b.projects.length>1000)fail(400,'Nieprawidłowa lista członków lub projektów.');
    for(const uid of b.members)if(!db.prepare("SELECT id FROM users WHERE id=? AND account_kind='human'").get(integer(uid,'Użytkownik')))fail(400,'Nieznane konto.');
    for(const pid of b.projects){const p=projects.requireProject(pid,u,true);if(p.project_type!=='external')fail(400,'Organizacje przypisuje się do projektów z portalem.');}
    return tx(()=>{let saved=id;if(old)db.prepare('UPDATE organizations SET name=?,share_tickets=?,version=version+1 WHERE id=?').run(name,share,id);else saved=Number(db.prepare('INSERT INTO organizations(name,share_tickets) VALUES(?,?)').run(name,share).lastInsertRowid);db.prepare('DELETE FROM organization_members WHERE organization_id=?').run(saved);db.prepare('DELETE FROM project_organizations WHERE organization_id=?').run(saved);for(const x of new Set(b.members))db.prepare('INSERT INTO organization_members VALUES(?,?)').run(saved,x);for(const x of new Set(b.projects))db.prepare('INSERT INTO project_organizations VALUES(?,?)').run(x,saved);projects.audit(null,u,'organization.updated',{organization_id:saved,share_tickets:Boolean(share)});return organizations(u).find(o=>o.id===saved);});
  }
  function templates(u){if(!['admin','agent'].includes(u.role))fail(403,'Dostęp zespołu.');return db.prepare('SELECT * FROM workflow_templates ORDER BY is_default DESC,name').all().map(t=>({...t,config:JSON.parse(t.config)}));}
  function templateSave(id,b,u){admin(u);const source=projects.requireProject(integer(b.project_id,'Projekt wzorcowy'),u,true),config=workflows.get(source.id);delete config.version;config.rules=[];const old=id?db.prepare('SELECT * FROM workflow_templates WHERE id=?').get(id):null;if(id&&(!old||old.version!==b.version))fail(409,'Szablon zmienił się.');return tx(()=>{if(b.is_default===true)db.exec('UPDATE workflow_templates SET is_default=0;');const name=text(b.name,'Nazwa szablonu',2,100);if(old)db.prepare('UPDATE workflow_templates SET name=?,config=?,is_default=?,version=version+1 WHERE id=?').run(name,JSON.stringify(config),Number(b.is_default===true),id);else id=Number(db.prepare('INSERT INTO workflow_templates(name,config,is_default) VALUES(?,?,?)').run(name,JSON.stringify(config),Number(b.is_default===true)).lastInsertRowid);projects.audit(source.id,u,'workflow.template_saved',{template_id:id});return templates(u).find(x=>x.id===id);});}
  function templateClone(id,b,u){admin(u);const old=db.prepare('SELECT * FROM workflow_templates WHERE id=?').get(id);if(!old)fail(404,'Szablon nie istnieje.');const saved=Number(db.prepare('INSERT INTO workflow_templates(name,config) VALUES(?,?)').run(text(b.name,'Nazwa kopii',2,100),old.config).lastInsertRowid);return templates(u).find(x=>x.id===saved);}
  function templateApply(id,b,u){const p=projects.requireProject(integer(b.project_id,'Projekt'),u,true),t=db.prepare('SELECT * FROM workflow_templates WHERE id=?').get(id);if(!t)fail(404,'Szablon nie istnieje.');const current=workflows.get(p.id);return workflows.save(p.id,{...JSON.parse(t.config),rules:current.rules,version:b.version},u);}
  function assets(u,projectId,q=''){if(!['admin','agent'].includes(u.role))fail(403,'Urządzenia są dostępne zespołowi.');q=text(q,'Szukaj',0,100).toLowerCase();return db.prepare('SELECT * FROM assets ORDER BY name').all().filter(a=>(!projectId||a.project_id===Number(projectId))&&projects.canWork(u,projects.project(a.project_id))&&(a.name+' '+a.asset_key+' '+a.serial).toLowerCase().includes(q)).slice(0,500).map(a=>({...a,data:JSON.parse(a.data)}));}
  function saveAsset(id,b,u){const old=id?db.prepare('SELECT * FROM assets WHERE id=?').get(id):null;if(id&&(!old||b.version!==old.version))fail(409,'Urządzenie zmieniło się.');const p=projects.requireProject(old?.project_id??integer(b.project_id,'Projekt urządzeń'),u);if(p.module_type!=='assets'||p.archived)fail(400,'Wybierz aktywny projekt środków trwałych.');const data=b.data??{};if(!data||typeof data!=='object'||Array.isArray(data)||JSON.stringify(data).length>20000)fail(400,'Dane urządzenia: obiekt do 20 000 znaków.');const owner=b.owner_id===null||b.owner_id===undefined?null:integer(b.owner_id,'Użytkownik');if(owner&&!db.prepare('SELECT id FROM users WHERE id=?').get(owner))fail(400,'Nieznany właściciel.');
    return tx(()=>{const values=[text(b.name,'Nazwa urządzenia',2,200),text(b.kind||'Urządzenie','Typ',1,100),text(b.serial||'','Numer seryjny',0,200),owner,text(b.status||'W użyciu','Stan',1,100),JSON.stringify(data),now()];if(old)db.prepare('UPDATE assets SET name=?,kind=?,serial=?,owner_id=?,status=?,data=?,updated_at=?,version=version+1 WHERE id=?').run(...values,id);else{const n=p.next_number;if(n>2000000000)fail(409,'Wyczerpana numeracja urządzeń.');const key=projects.issueKey(p,n);db.prepare('UPDATE projects SET next_number=next_number+1,version=version+1 WHERE id=?').run(p.id);id=Number(db.prepare('INSERT INTO assets(name,kind,serial,owner_id,status,data,updated_at,project_id,asset_key,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)').run(...values,p.id,key,now()).lastInsertRowid);}projects.audit(p.id,u,'asset.updated',{asset_id:id});return assets(u,p.id).find(a=>a.id===id);});
  }
  function attach(ticketId,assetId,remove,u){const t=desk.requireTicket(ticketId,u),a=db.prepare('SELECT * FROM assets WHERE id=?').get(integer(assetId,'Urządzenie')),p=projects.project(t.project_id);if(t.status==='closed')fail(409,'Zamknięta sprawa jest ostateczna.');if(!a||!projects.canWork(u,projects.project(a.project_id))||!(desk.settings(p).asset_projects||[]).includes(a.project_id))fail(403,'Projekt nie dopuszcza urządzeń z tego katalogu.');if(remove)db.prepare('DELETE FROM ticket_assets WHERE ticket_id=? AND asset_id=?').run(t.id,a.id);else db.prepare('INSERT OR IGNORE INTO ticket_assets VALUES(?,?)').run(t.id,a.id);projects.audit(p.id,u,'ticket.asset_linked',{ticket_id:t.id,asset_id:a.id,removed:Boolean(remove)});return {ok:true};}
  return {organizations,saveOrganization,templates,templateSave,templateClone,templateApply,assets,saveAsset,attach};
}
