import * as oidc from 'openid-client';
import {randomBytes,createHash} from 'node:crypto';
import {fail,now,text,email,integer,boolean,txFor} from './core.mjs';
import {secretStore} from './secrets.mjs';
import {username,parts} from './usernames.mjs';
const hash=v=>createHash('sha256').update(v).digest('hex');
const isGithub=p=>{try{const u=new URL(p.issuer);return u.protocol==='https:'&&u.hostname.toLowerCase()==='github.com'&&(u.pathname==='/'||u.pathname==='');}catch{return false;}};
export function createSso(db,projects,{origin,dataDir,clock=Date.now,allowTestHttp=false,fetcher=fetch}){
  const tx=txFor(db),secrets=secretStore(dataDir),cache=new Map();
  const admin=u=>{if(u.role!=='admin')fail(403,'Wymagany administrator.');};
  const row=id=>db.prepare('SELECT * FROM sso_providers WHERE id=?').get(integer(Number(id),'Dostawca SSO'));
  const output=r=>{const {secret,...out}=r;return {...out,enabled:Boolean(r.enabled),config:JSON.parse(r.config),has_secret:Boolean(secret),callback_url:origin+'/api/sso/callback',provider_type:isGithub(r)?'github':'oidc'};};
  function list(u){if(u){admin(u);return db.prepare('SELECT * FROM sso_providers ORDER BY name').all().map(output);}return db.prepare('SELECT id,name FROM sso_providers WHERE enabled=1 ORDER BY name').all();}
  function save(id,b,u){admin(u);const old=id?row(id):null;if(id&&(!old||old.version!==b.version))fail(409,'Ustawienia SSO zmieniły się.');let issuer;try{issuer=new URL(b.issuer);}catch{fail(400,'Podaj adres issuer dostawcy OpenID Connect albo https://github.com dla GitHub OAuth.');}if((issuer.protocol!=='https:'&&!(allowTestHttp&&issuer.protocol==='http:'))||issuer.username||issuer.password||issuer.search||issuer.hash)fail(400,'Issuer wymaga HTTPS, bez danych logowania i parametrów.');if(issuer.hostname.toLowerCase()==='github.com')issuer=new URL('https://github.com/');
    const c=b.config||{},domains=c.allowed_domains||[];if(!Array.isArray(domains)||domains.length>100)fail(400,'Nieprawidłowe domeny SSO.');const cfg={auto_create:boolean(c.auto_create??false,'Tworzenie nowych kont'),allowed_domains:domains.map(d=>email('test@'+d).split('@')[1]),provider_type:issuer.hostname.toLowerCase()==='github.com'?'github':'oidc'};const secret=b.client_secret?secrets.seal(text(b.client_secret,'Sekret klienta',1,4000)):old?.secret||'';
    return tx(()=>{const vals=[text(b.name,'Nazwa dostawcy',2,100),issuer.href,text(b.client_id,'Client ID',1,300),secret,JSON.stringify(cfg),Number(boolean(b.enabled??false,'SSO aktywne'))];if(old)db.prepare('UPDATE sso_providers SET name=?,issuer=?,client_id=?,secret=?,config=?,enabled=?,version=version+1 WHERE id=?').run(...vals,id);else id=Number(db.prepare('INSERT INTO sso_providers(name,issuer,client_id,secret,config,enabled) VALUES(?,?,?,?,?,?)').run(...vals).lastInsertRowid);cache.delete(id);projects.audit(null,u,'sso.configured',{provider_id:id,provider_type:cfg.provider_type});return output(row(id));});
  }
  async function config(p){if(isGithub(p))return null;const found=cache.get(p.id);if(found&&found.version===p.version&&found.until>clock())return found.value;const value=await oidc.discovery(new URL(p.issuer),p.client_id,p.secret?secrets.open(p.secret):undefined,undefined,{timeout:10,...(allowTestHttp?{execute:[oidc.allowInsecureRequests]}:{})});cache.set(p.id,{value,version:p.version,until:clock()+300000});return value;}
  async function githubJson(url,options={}){const res=await fetcher(url,{...options,headers:{Accept:'application/json','User-Agent':'iTELade-Service-Desk',...(options.headers||{})},signal:AbortSignal.timeout(10000)}),raw=await res.text();let value={};try{value=raw?JSON.parse(raw):{};}catch{}if(!res.ok)fail(502,`GitHub OAuth ${res.status}: ${raw.slice(0,180)}`);return value;}
  async function begin(id){const p=row(id);if(!p?.enabled)fail(404,'Dostawca SSO jest niedostępny.');const state=oidc.randomState(),browser=randomBytes(32).toString('hex');db.prepare('DELETE FROM sso_states WHERE expires_at<?').run(clock());
    if(isGithub(p)){
      db.prepare('INSERT INTO sso_states VALUES(?,?,?,?)').run(hash(state),p.id,secrets.seal(JSON.stringify({state,browser:hash(browser),version:p.version,provider_type:'github'})),clock()+600000);
      const url=new URL('https://github.com/login/oauth/authorize');url.searchParams.set('client_id',p.client_id);url.searchParams.set('redirect_uri',origin+'/api/sso/callback');url.searchParams.set('scope','read:user user:email');url.searchParams.set('state',state);return {url:url.href,browser};
    }
    const c=await config(p),nonce=oidc.randomNonce(),verifier=oidc.randomPKCECodeVerifier();db.prepare('INSERT INTO sso_states VALUES(?,?,?,?)').run(hash(state),p.id,secrets.seal(JSON.stringify({state,nonce,verifier,browser:hash(browser),version:p.version,provider_type:'oidc'})),clock()+600000);
    const url=oidc.buildAuthorizationUrl(c,{redirect_uri:origin+'/api/sso/callback',scope:'openid profile email',state,nonce,code_challenge:await oidc.calculatePKCECodeChallenge(verifier),code_challenge_method:'S256'});return {url:url.href,browser};
  }
  function finishIdentity(p,subject,profile){
    return tx(()=>{if(row(p.id)?.version!==p.version||!row(p.id).enabled)fail(409,'Dostawca SSO został zmieniony.');const mapping=db.prepare('SELECT user_id FROM sso_subjects WHERE provider_id=? AND subject=?').get(p.id,String(subject));let id=mapping?.user_id;
      if(!id){const c=JSON.parse(p.config);if(!c.auto_create||profile.email_verified!==true)fail(403,'Administrator musi powiązać tożsamość SSO z kontem lub zezwolić na tworzenie zweryfikowanych kont.');const mail=email(profile.email);if(c.allowed_domains.length&&!c.allowed_domains.includes(mail.split('@')[1]))fail(403,'Domena nie jest dopuszczona dla tego dostawcy.');if(db.prepare('SELECT id FROM users WHERE email=?').get(mail))fail(403,'Adres ma już konto. Administrator musi powiązać istniejące konto z identyfikatorem SSO.');const n=parts(text(profile.name||[profile.given_name,profile.family_name].filter(Boolean).join(' ')||profile.login||mail.split('@')[0],'Nazwa profilu',1,100));id=Number(db.prepare("INSERT INTO users(email,name,first_name,last_name,username,password,role,must_change,sso_only,email_verified,created_at) VALUES(?,?,?,?,?,'!sso','customer',0,1,1,?)").run(mail,(n.first_name+' '+n.last_name).trim(),n.first_name,n.last_name,username(db,n.first_name,n.last_name),now()).lastInsertRowid);db.prepare('INSERT INTO sso_subjects VALUES(?,?,?)').run(p.id,String(subject),id);projects.audit(null,{id},'sso.account_created',{provider_id:p.id,provider_type:isGithub(p)?'github':'oidc'});}
      if(profile.email_verified===true&&profile.email){const verified=email(profile.email),collision=db.prepare('SELECT id FROM users WHERE email=? AND id<>?').get(verified,id);const current=db.prepare('SELECT email,email_verified FROM users WHERE id=?').get(id);if(!collision&&(!current.email_verified||String(current.email).endsWith('.invalid')))db.prepare('UPDATE users SET email=?,email_verified=1,version=version+1 WHERE id=?').run(verified,id);}
      const u=db.prepare('SELECT * FROM users WHERE id=?').get(id);if(!u?.active||!u.directory_active||u.registration_state!=='active'||u.account_kind!=='human')fail(403,'Konto jest wyłączone lub nie może logować się interaktywnie.');projects.audit(null,u,'sso.login',{provider_id:p.id,provider_type:isGithub(p)?'github':'oidc'});return u;});
  }
  async function callback(url,browser){const state=url.searchParams.get('state');if(!state||!browser)fail(400,'Brak sesji rozpoczęcia logowania SSO.');const r=db.prepare('SELECT * FROM sso_states WHERE state=? AND expires_at>?').get(hash(state),clock());if(!r)fail(400,'Sesja SSO wygasła lub została już wykorzystana.');const saved=JSON.parse(secrets.open(r.payload));if(saved.browser!==hash(browser))fail(403,'Odpowiedź SSO nie należy do tej przeglądarki.');db.prepare('DELETE FROM sso_states WHERE state=?').run(r.state);const p=row(r.provider_id);if(!p?.enabled||p.version!==saved.version)fail(409,'Konfiguracja SSO zmieniła się. Rozpocznij ponownie.');
    if(isGithub(p)){
      const code=url.searchParams.get('code');if(!code)fail(400,'GitHub nie zwrócił kodu autoryzacji.');const token=await githubJson('https://github.com/login/oauth/access_token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:p.client_id,client_secret:secrets.open(p.secret),code,redirect_uri:origin+'/api/sso/callback',state:saved.state}).toString()});if(!token.access_token)fail(403,'GitHub nie zwrócił tokenu logowania.');const headers={Authorization:'Bearer '+token.access_token},profile=await githubJson('https://api.github.com/user',{headers});if(!profile?.id)fail(403,'GitHub nie zwrócił identyfikatora użytkownika.');let verified=null;try{const emails=await githubJson('https://api.github.com/user/emails',{headers});if(Array.isArray(emails))verified=emails.find(x=>x.primary&&x.verified)?.email||emails.find(x=>x.verified)?.email||null;}catch{}return finishIdentity(p,String(profile.id),{...profile,email:verified||profile.email||null,email_verified:Boolean(verified),name:profile.name||profile.login});
    }
    const cfg=await config(p),tokens=await oidc.authorizationCodeGrant(cfg,url,{pkceCodeVerifier:saved.verifier,expectedState:saved.state,expectedNonce:saved.nonce,idTokenExpected:true}),claims=tokens.claims();if(!claims?.sub)fail(403,'Dostawca nie zwrócił identyfikatora użytkownika.');let profile=claims;if(!profile.email&&cfg.serverMetadata().userinfo_endpoint)profile={...claims,...await oidc.fetchUserInfo(cfg,tokens.access_token,claims.sub)};return finishIdentity(p,claims.sub,profile);
  }
  function mapping(id,b,u){admin(u);if(!row(id))fail(404,'Dostawca nie istnieje.');const user=db.prepare("SELECT * FROM users WHERE id=? AND account_kind='human'").get(integer(b.user_id,'Konto'));if(!user)fail(400,'Wybierz konto człowieka.');const subject=text(b.subject,'Subject (sub) dostawcy',1,300);db.prepare('INSERT INTO sso_subjects VALUES(?,?,?) ON CONFLICT(provider_id,subject) DO UPDATE SET user_id=excluded.user_id').run(id,subject,user.id);projects.audit(null,u,'sso.identity_linked',{provider_id:id,subject,user_id:user.id});return {ok:true};}
  return {list,save,begin,callback,mapping};
}
