import {maintenance} from './maintenance.mjs';
import http from 'node:http';
import https from 'node:https';
import {lookup} from 'node:dns/promises';
import {isIP} from 'node:net';
import {randomBytes,createHmac,createHash,timingSafeEqual} from 'node:crypto';
import {fail,now,text,integer,boolean,choice,txFor} from './core.mjs';
import {secretStore} from './secrets.mjs';
export function allowedAddress(address,privateAllowed=false){
  const a=address.toLowerCase().replace(/^::ffff:/,'');
  if(!isIP(a)||a==='::'||a==='::1'||a.startsWith('fe80:')||a.startsWith('ff')||/^(0|127|169\.254|22[4-9]|23\d|24\d|25[0-5])\./.test(a))return false;
  const privateIp=/^(10\.|192\.168\.|172\.(1[6-9]|2\d|3[01])\.|100\.(6[4-9]|[7-9]\d|1[01]\d|12[0-7])\.)/.test(a)||/^(fc|fd)/.test(a);return privateAllowed||!privateIp;
}
export async function deliverWebhook(url,body,headers,allowPrivate){const u=new URL(url),hostname=u.hostname.replace(/^\[|\]$/g,''),answers=await lookup(hostname,{all:true});if(!answers.length||answers.some(x=>!allowedAddress(x.address,allowPrivate)))fail(400,'Adres webhooka prowadzi do niedozwolonej sieci.');const selected=answers[0];return new Promise((resolve,reject)=>{const req=(u.protocol==='https:'?https:http).request(u,{method:'POST',headers:{'Content-Type':'application/json','Content-Length':Buffer.byteLength(body),...headers},lookup:(_host,opts,cb)=>opts.all?cb(null,[selected]):cb(null,selected.address,selected.family),timeout:8000},res=>{res.resume();if(res.statusCode>=200&&res.statusCode<300)resolve();else reject(new Error('HTTP_'+res.statusCode));});req.on('timeout',()=>req.destroy(new Error('TIMEOUT')));req.on('error',reject);req.end(body);});}
export function createWebhooks(db,projects,desk,workflows,{dataDir,clock=Date.now,send=deliverWebhook}){
  const secrets=secretStore(dataDir),tx=txFor(db);let busy=false,timer;
  const row=id=>db.prepare('SELECT * FROM webhook_endpoints WHERE id=?').get(id),output=r=>{const {secret,...out}=r;return {...out,config:JSON.parse(r.config),enabled:Boolean(r.enabled)};};
  function list(u){return db.prepare('SELECT * FROM webhook_endpoints ORDER BY name').all().filter(r=>projects.canManage(u,projects.project(r.project_id))).map(output);}
  function save(id,b,u){const old=id?row(id):null;if(id&&(!old||old.version!==b.version))fail(409,'Webhook zmienił się.');if(old)projects.requireProject(old.project_id,u,true);const p=projects.requireProject(integer(b.project_id,'Projekt'),u,true),direction=choice(b.direction,['inbound','outbound'],'Kierunek'),c=b.config||{};if(old&&(p.id!==old.project_id||direction!==old.direction))fail(400,'Dla innego projektu lub kierunku utwórz nowy webhook.');const cfg={events:(c.events||[]).map(v=>choice(v,['ticket_created','status_changed','comment_added'],'Zdarzenie')),include_internal:boolean(c.include_internal??false,'Notatki wewnętrzne'),allow_private:boolean(c.allow_private??false,'Sieci prywatne')};
    if(direction==='outbound'){let url;try{url=new URL(c.url);}catch{fail(400,'Nieprawidłowy URL.');}if(!['https:','http:'].includes(url.protocol)||url.username||url.password||url.hash)fail(400,'URL webhooka wymaga HTTP(S), bez hasła i fragmentu.');if(url.protocol==='http:'&&!cfg.allow_private)fail(400,'Publiczny webhook wymaga HTTPS.');cfg.url=url.href;}
    else{const bot=db.prepare("SELECT * FROM users WHERE id=? AND active=1").get(integer(c.bot_id,'Konto'));if(!bot||!projects.canWork(bot,p))fail(400,'Bot musi obsługiwać ten projekt.');cfg.bot_id=bot.id;}
    const generated=old&&!b.rotate_secret?null:randomBytes(32).toString('hex'),secret=generated?secrets.seal(generated):old.secret;
    return tx(()=>{const vals=[text(b.name,'Nazwa webhooka',2,100),p.id,direction,JSON.stringify(cfg),secret,Number(boolean(b.enabled??true,'Aktywny'))];if(old)db.prepare('UPDATE webhook_endpoints SET name=?,project_id=?,direction=?,config=?,secret=?,enabled=?,version=version+1 WHERE id=?').run(...vals,id);else id=Number(db.prepare('INSERT INTO webhook_endpoints(name,project_id,direction,config,secret,enabled) VALUES(?,?,?,?,?,?)').run(...vals).lastInsertRowid);projects.audit(p.id,u,'webhook.configured',{webhook_id:id});return {...output(row(id)),...(generated?{generated_secret:generated}:{})};});
  }
  function enqueue(id,t,event,actorId,payload={}){const r=row(id);if(!r?.enabled||r.direction!=='outbound'||r.project_id!==t.project_id)fail(400,'Webhook nie jest dostępny.');const body={event,event_id:randomBytes(16).toString('hex'),occurred_at:now(),ticket:{key:t.key,title:t.title,status:t.workflow_status,category:t.status},actor_id:actorId??null,...payload};db.prepare('INSERT INTO webhook_jobs(endpoint_id,payload,next_attempt,created_at) VALUES(?,?,?,?)').run(id,JSON.stringify(body),clock(),now());}
  function notify(event){const t=desk.ticket(event.ticket_id),payload=JSON.parse(event.payload),c=event.event==='comment_added'?db.prepare('SELECT * FROM comments WHERE id=?').get(payload.comment_id):null;for(const r of db.prepare("SELECT * FROM webhook_endpoints WHERE project_id=? AND direction='outbound' AND enabled=1").all(t.project_id)){const cfg=JSON.parse(r.config);if(!cfg.events.includes(event.event)||(c?.internal&&!cfg.include_internal))continue;enqueue(r.id,t,event.event,c?.actual_actor_id||c?.author_id||t.created_by,c?{comment:{id:c.id,body:c.body,internal:Boolean(c.internal)}}:{});}}
  function incoming(id,authorization,b){const r=row(integer(Number(id),'Webhook'));if(!r?.enabled||r.direction!=='inbound')fail(404,'Webhook niedostępny.');const raw=String(authorization||'').replace(/^Bearer /,''),expected=secrets.open(r.secret),a=createHash('sha256').update(raw).digest(),z=createHash('sha256').update(expected).digest();if(!timingSafeEqual(a,z))fail(401,'Nieprawidłowy sekret webhooka.');const receipt=text(b.event_id,'Unikalny event_id',1,200),key=text(b.ticket_key,'Numer sprawy',3,30),t=db.prepare('SELECT * FROM tickets WHERE key=? AND project_id=?').get(key,r.project_id);if(!t||t.deleted_at)fail(404,'Nieznana sprawa.');if(t.archived_at||projects.project(t.project_id).archived)fail(409,'Sprawa lub projekt jest w archiwum.');if(t.status==='closed')fail(409,'Zamknięta sprawa jest ostateczna.');return tx(()=>{if(db.prepare('SELECT 1 FROM webhook_receipts WHERE endpoint_id=? AND receipt=?').get(r.id,receipt))return {ok:true,duplicate:true};const cfg=JSON.parse(r.config),bot=db.prepare("SELECT * FROM users WHERE id=? AND active=1").get(cfg.bot_id);if(!bot||!projects.canWork(bot,projects.project(r.project_id)))fail(403,'Bot utracił dostęp.');db.prepare('INSERT INTO webhook_receipts VALUES(?,?,?)').run(r.id,receipt,now());workflows.automation.emit(t.id,'webhook_received',bot,undefined,{origin:'webhook',author_kind:'service'});projects.audit(r.project_id,bot,'webhook.received',{webhook_id:r.id,ticket_id:t.id,event_id:receipt});return {ok:true};});}
  async function flush(){if(maintenance())return;if(busy)return;busy=true;try{for(const j of db.prepare("SELECT * FROM webhook_jobs WHERE status='queued' AND next_attempt<=? ORDER BY id LIMIT 20").all(clock())){const r=row(j.endpoint_id);if(!r?.enabled)continue;const c=JSON.parse(r.config),stamp=String(clock()),signature=createHmac('sha256',secrets.open(r.secret)).update(stamp+'.'+j.payload).digest('hex');try{await send(c.url,j.payload,{'X-ServiceDesk-Timestamp':stamp,'X-ServiceDesk-Signature':'sha256='+signature,'X-ServiceDesk-Delivery':String(j.id),'X-iTELade-Timestamp':stamp,'X-iTELade-Signature':'sha256='+signature,'X-iTELade-Delivery':String(j.id)},c.allow_private);db.prepare("UPDATE webhook_jobs SET status='sent',attempts=attempts+1,last_error=NULL WHERE id=?").run(j.id);}catch(e){const attempts=j.attempts+1;db.prepare('UPDATE webhook_jobs SET attempts=?,status=?,next_attempt=?,last_error=? WHERE id=?').run(attempts,attempts>=5?'failed':'queued',clock()+2**attempts*60000,String(e.status?e.message:e.code||e.message||'DELIVERY_FAILED').slice(0,300),j.id);}}}finally{busy=false;}}
  function jobs(u){const ids=list(u).map(r=>r.id);return db.prepare('SELECT * FROM webhook_jobs ORDER BY id DESC LIMIT 200').all().filter(j=>ids.includes(j.endpoint_id)).map(({payload,...j})=>j);}
  return {list,save,enqueue,notify,incoming,flush,jobs,start(){timer=setInterval(()=>void flush(),15000).unref();},stop(){clearInterval(timer);}};
}
