import {readFileSync,writeFileSync} from 'node:fs';

const read=p=>readFileSync(p,'utf8');
const write=(p,s)=>writeFileSync(p,s);
function once(s,from,to,label){
  const n=s.split(from).length-1;
  if(n!==1)throw new Error(`${label}: expected one match, got ${n}`);
  return s.replace(from,to);
}
function replaceAllCount(s,from,to,min,label){
  const n=s.split(from).length-1;
  if(n<min)throw new Error(`${label}: expected at least ${min} matches, got ${n}`);
  return s.replaceAll(from,to);
}

let projects=read('lib/projects.mjs');
projects=once(projects,
`  function canWork(user,p){return user.role==='admin'||(user.role==='agent'&&['manager','agent'].includes(memberRole(user,p)));}\n  function canManage(user,p){return user.role==='admin'||(user.role==='agent'&&memberRole(user,p)==='manager');}\n  function canPortal(user,p){\n    if(p.project_type!=='external')return false;\n    if(user.role==='admin')return true;\n    if(p.portal_access==='internal')return Boolean(user.is_internal);\n    if(canWork(user,p))return true;\n    if(p.portal_access==='authenticated')return true;\n    return Boolean(memberRole(user,p)||db.prepare('SELECT 1 FROM organization_members m JOIN project_organizations po ON po.organization_id=m.organization_id WHERE m.user_id=? AND po.project_id=?').get(user.id,p.id));\n  }\n  const organizationAccess=(user,p,t)=>Boolean(t.organization_id&&db.prepare('SELECT o.id FROM organizations o JOIN organization_members m ON m.organization_id=o.id JOIN project_organizations po ON po.organization_id=o.id WHERE o.id=? AND m.user_id=? AND po.project_id=? AND o.share_tickets=1').get(t.organization_id,user.id,p.id));\n  const canRead=(user,p,t)=>Boolean(t&&p&&!t.deleted_at&&(canWork(user,p)||((t.reporter_id===user.id||organizationAccess(user,p,t))&&canPortal(user,p))));`,
`  function canWork(user,p){return user.role==='admin'||(user.role==='agent'&&['manager','agent'].includes(memberRole(user,p)));}\n  function canManage(user,p){return user.role==='admin'||(user.role==='agent'&&memberRole(user,p)==='manager');}\n  const githubIdentity=user=>Boolean(user&&db.prepare(\"SELECT 1 FROM sso_subjects s JOIN sso_providers p ON p.id=s.provider_id WHERE s.user_id=? AND p.enabled=1 AND lower(rtrim(p.issuer,'/'))='https://github.com' LIMIT 1\").get(user.id));\n  const publicReadable=p=>Boolean(p&&p.project_type==='external'&&p.portal_access==='public_github'&&!p.archived);\n  function canPortal(user,p){\n    if(p.project_type!=='external')return false;\n    if(user.role==='admin')return true;\n    if(canWork(user,p))return true;\n    if(p.portal_access==='public_github')return githubIdentity(user);\n    if(p.portal_access==='internal')return Boolean(user.is_internal);\n    if(p.portal_access==='authenticated'){\n      if(user.sso_only&&githubIdentity(user))return Boolean(memberRole(user,p));\n      return true;\n    }\n    return Boolean(memberRole(user,p)||db.prepare('SELECT 1 FROM organization_members m JOIN project_organizations po ON po.organization_id=m.organization_id WHERE m.user_id=? AND po.project_id=?').get(user.id,p.id));\n  }\n  const organizationAccess=(user,p,t)=>Boolean(t.organization_id&&db.prepare('SELECT o.id FROM organizations o JOIN organization_members m ON m.organization_id=o.id JOIN project_organizations po ON po.organization_id=o.id WHERE o.id=? AND m.user_id=? AND po.project_id=? AND o.share_tickets=1').get(t.organization_id,user.id,p.id));\n  const canRead=(user,p,t)=>Boolean(t&&p&&!t.deleted_at&&(canWork(user,p)||(publicReadable(p)&&githubIdentity(user))||((t.reporter_id===user.id||organizationAccess(user,p,t))&&canPortal(user,p))));`,
'project access model');
projects=once(projects,
"    out.portal_access=choice(out.portal_access??'members',['members','internal','authenticated'],'dostęp do portalu');",
"    out.portal_access=choice(out.portal_access??'members',['members','internal','authenticated','public_github'],'dostęp do portalu');",
'portal access enum');
projects=once(projects,
"  return {project,view,list,canWork,canManage,canPortal,canRead,requireProject,ticketScope,create,update,members,setMember,candidates,agents,issueKey,audit,clearAssignments};",
"  return {project,view,list,canWork,canManage,canPortal,canRead,githubIdentity,publicReadable,requireProject,ticketScope,create,update,members,setMember,candidates,agents,issueKey,audit,clearAssignments};",
'projects exports');
write('lib/projects.mjs',projects);

let sso=read('lib/sso.mjs');
sso=once(sso,
"  function list(u){if(u){admin(u);return db.prepare('SELECT * FROM sso_providers ORDER BY name').all().map(output);}return db.prepare('SELECT id,name FROM sso_providers WHERE enabled=1 ORDER BY name').all();}",
"  function list(u){if(u){admin(u);return db.prepare('SELECT * FROM sso_providers ORDER BY name').all().map(output);}return db.prepare('SELECT id,name,issuer FROM sso_providers WHERE enabled=1 ORDER BY name').all().map(r=>({id:r.id,name:r.name,provider_type:isGithub(r)?'github':'oidc'}));}",
'public SSO provider type');
write('lib/sso.mjs',sso);

let server=read('server.mjs');
server=once(server,
"    if(method==='POST'&&['/api/register','/api/resend-verification','/api/forgot-password','/api/verify-email','/api/reset-password'].includes(pathname)){\n      rateLimit('account-total',200);const b=await body(req);\n      if(b.email)rateLimit('account:'+digest(String(b.email).trim().toLowerCase()),8);\n      if(b.token)rateLimit('token:'+digest(String(b.token)),10);\n      const result=pathname==='/api/register'?await accounts.register(b):pathname==='/api/verify-email'?accounts.verify(b.token):pathname==='/api/reset-password'?await accounts.reset(b.token,b.password):accounts.resend(b.email,pathname==='/api/forgot-password'?'reset':'verify');\n      return json(res,200,result);\n    }\n    let user=session(req);",
"    if(method==='POST'&&['/api/register','/api/resend-verification','/api/forgot-password','/api/verify-email','/api/reset-password'].includes(pathname)){\n      rateLimit('account-total',200);const b=await body(req);\n      if(b.email)rateLimit('account:'+digest(String(b.email).trim().toLowerCase()),8);\n      if(b.token)rateLimit('token:'+digest(String(b.token)),10);\n      const result=pathname==='/api/register'?await accounts.register(b):pathname==='/api/verify-email'?accounts.verify(b.token):pathname==='/api/reset-password'?await accounts.reset(b.token,b.password):accounts.resend(b.email,pathname==='/api/forgot-password'?'reset':'verify');\n      return json(res,200,result);\n    }\n    const publicPortal=pathname.match(/^\\/api\\/public\\/portals\\/([a-z0-9]+(?:-[a-z0-9]+)*)(?:\\/tickets\\/([A-Z][A-Z0-9]{1,9}-[0-9]{1,10}))?$/);\n    if(method==='GET'&&publicPortal){\n      const p=db.prepare('SELECT * FROM projects WHERE portal_slug=?').get(publicPortal[1]);\n      if(!projects.publicReadable(p))fail(404,'Publiczny portal nie istnieje.');\n      const project={id:p.id,key:p.key,name:p.name,description:p.description,portal_slug:p.portal_slug,portal_title:p.portal_title,portal_description:p.portal_description,portal_access:p.portal_access};\n      const github_sso=sso.list().find(x=>x.provider_type==='github')||null;\n      if(publicPortal[2]){\n        const t=db.prepare(`SELECT t.key,t.title,t.description,t.status,t.workflow_status,t.priority,t.created_at,t.updated_at,u.name reporter_name FROM tickets t JOIN users u ON u.id=t.reporter_id WHERE t.project_id=? AND t.key=? AND t.deleted_at IS NULL AND t.archived_at IS NULL`).get(p.id,publicPortal[2]);\n        if(!t)fail(404,'Zgłoszenie nie istnieje.');\n        const comments=db.prepare(`SELECT c.body,c.created_at,c.origin IN ('automation','sync') is_bot,u.name author_name FROM comments c JOIN users u ON u.id=c.author_id WHERE c.ticket_id=(SELECT id FROM tickets WHERE project_id=? AND key=?) AND c.internal=0 ORDER BY c.id`).all(p.id,t.key);\n        return json(res,200,{project,ticket:t,comments,github_sso});\n      }\n      const tickets=db.prepare(`SELECT t.key,t.title,t.description,t.status,t.workflow_status,t.priority,t.created_at,t.updated_at,u.name reporter_name FROM tickets t JOIN users u ON u.id=t.reporter_id WHERE t.project_id=? AND t.deleted_at IS NULL AND t.archived_at IS NULL ORDER BY t.updated_at DESC,t.id DESC LIMIT 100`).all(p.id);\n      return json(res,200,{project,tickets,github_sso});\n    }\n    let user=session(req);",
'public portal API');
write('server.mjs',server);

let app=read('public/app.js');
app=once(app,
"const brand=()=>S.meta?.brand_name||S.config.brand_name||'Service Desk';",
"const brand=()=>S.meta?.brand_name||S.config.brand_name||'Service Desk';\nconst githubProvider=()=> (S.config.sso_providers||[]).find(p=>p.provider_type==='github');",
'GitHub provider helper');
app=once(app,
"const accessNames={members:'Wybrani członkowie',internal:'Tylko konta firmowe',authenticated:'Wszyscy zalogowani'};",
"const accessNames={members:'Wybrani członkowie',internal:'Tylko konta firmowe',authenticated:'Wszyscy zalogowani',public_github:'Publiczny odczyt · zapis po logowaniu GitHub'};",
'portal access label');
app=once(app,
"async function api(path, {method = 'GET', data} = {}) {\n  const response = await fetch('/api' + path, {method, credentials:'same-origin', headers: { 'Content-Type':'application/json', 'X-CSRF-Token':S.csrf }, ...(data === undefined ? {} : {body:JSON.stringify(data)})});",
"async function publicApi(path){const response=await fetch('/api/public'+path,{credentials:'same-origin'});let value;try{value=await response.json();}catch{throw new Error('Serwer nie zwrócił poprawnej odpowiedzi.');}if(!response.ok)throw new Error(value.error||'Nie udało się wczytać publicznego portalu.');return value;}\nasync function api(path, {method = 'GET', data} = {}) {\n  const response = await fetch('/api' + path, {method, credentials:'same-origin', headers: { 'Content-Type':'application/json', 'X-CSRF-Token':S.csrf }, ...(data === undefined ? {} : {body:JSON.stringify(data)})});",
'public API helper');
const oldPortalShell=`function portalShell(){\n  app.innerHTML=\`<div class="portal-workspace"><header class="portal-top"><a class="portal-brand" href="\${portalPath?'/portal/'+e(portalPath):'/#/portal'}"><img src="\${e(S.config.logo_url||'/favicon.svg')}" width="34" height="34" alt=""><span>\${e(brand())}</span></a><nav><a href="/#/portal">Portale</a><a href="\${portalPath?'#/queue?own=1':'/#/queue?own=1'}">Moje zgłoszenia</a>\${isStaff()?'<a href="/#/queue">Panel zespołu</a><a href="/#/projects">Projekty</a>':''}\${S.user.role==='admin'?'<a href="/#/projects/new">Nowy projekt</a><a href="/#/settings">Administracja</a>':''}\${isStaff()?notificationBell():''}<button data-extra-action="profile-open">Moje konto</button><button data-action="logout">Wyloguj</button></nav></header><main id="main" tabindex="-1"><div class="loading">Wczytywanie…</div></main><footer class="portal-footer">Obsługa klienta · Obsługa zgłoszeń</footer></div>\`;\n}`;
const newPortalShell=`function portalShell(){\n  const signed=Boolean(S.user),gh=githubProvider(),login=gh?\`/api/sso/\${gh.id}/start\`:'/#/login';\n  const account=signed?\`<a href="\${portalPath?'#/queue?own=1':'/#/queue?own=1'}">Moje zgłoszenia</a>\${isStaff()?'<a href="/#/queue">Panel zespołu</a><a href="/#/projects">Projekty</a>':''}\${S.user?.role==='admin'?'<a href="/#/projects/new">Nowy projekt</a><a href="/#/settings">Administracja</a>':''}\${isStaff()?notificationBell():''}<button data-extra-action="profile-open">Moje konto</button><button data-action="logout">Wyloguj</button>\`:\`<a class="button primary" href="\${e(login)}">Zaloguj przez GitHub</a>\`;\n  app.innerHTML=\`<div class="portal-workspace"><header class="portal-top"><a class="portal-brand" href="\${portalPath?'/portal/'+e(portalPath):'/#/portal'}"><img src="\${e(S.config.logo_url||'/favicon.svg')}" width="34" height="34" alt=""><span>\${e(brand())}</span></a><nav>\${signed?'<a href="/#/portal">Portale</a>':''}\${account}</nav></header><main id="main" tabindex="-1"><div class="loading">Wczytywanie…</div></main><footer class="portal-footer">Obsługa klienta · Obsługa zgłoszeń</footer></div>\`;\n}`;
app=once(app,oldPortalShell,newPortalShell,'anonymous portal shell');
app=once(app,
"function authCard(title,content){document.title=title+' · '+brand();",
"async function publicProjectPortalView(){const d=await publicApi('/portals/'+portalPath),p=d.project,login=d.github_sso?'/api/sso/'+d.github_sso.id+'/start':'/#/login';return heading(p.key,p.portal_title||p.name,`<a class=\"button primary\" href=\"${e(login)}\">Zaloguj przez GitHub, aby utworzyć zgłoszenie</a>`)+`<p class=\"lead\">${e(p.portal_description||p.description||'Publiczne zgłoszenia projektu.')}</p><section class=\"panel\"><div class=\"table-scroll\"><table><thead><tr><th>Zgłoszenie</th><th>Status</th><th>Priorytet</th><th>Aktualizacja</th></tr></thead><tbody>${d.tickets.map(t=>`<tr><td><a class=\"issue-title\" href=\"#/ticket/${e(t.key)}\"><span class=\"key\">${e(t.key)}</span><span>${e(t.title)}</span></a><small class=\"row-meta\">${e(t.description)}</small></td><td><span class=\"pill\">${e(t.workflow_status||t.status)}</span></td><td>${e(t.priority)}</td><td>${date(t.updated_at)}</td></tr>`).join('')||'<tr><td colspan=\"4\">Brak publicznych zgłoszeń.</td></tr>'}</tbody></table></div></section>`;}\nasync function publicProjectTicketView(key){const d=await publicApi('/portals/'+portalPath+'/tickets/'+encodeURIComponent(key)),t=d.ticket,login=d.github_sso?'/api/sso/'+d.github_sso.id+'/start':'/#/login';return heading(d.project.key,t.key,`<a class=\"button primary\" href=\"${e(login)}\">Zaloguj przez GitHub, aby skomentować</a>`)+`<section class=\"panel detail-panel\"><h2>${e(t.title)}</h2><div class=\"ticket-description\">${e(t.description).replaceAll('\\n','<br>')}</div><div class=\"button-row\"><span class=\"pill\">${e(t.workflow_status||t.status)}</span><span>${e(t.priority)}</span></div></section><section class=\"panel detail-panel\"><h2>Komentarze publiczne</h2>${d.comments.map(c=>`<article class=\"comment\"><div class=\"comment-meta\"><strong>${e(c.author_name)}${c.is_bot?' · Bot':''}</strong><time>${date(c.created_at)}</time></div><p>${e(c.body).replaceAll('\\n','<br>')}</p></article>`).join('')||'<p>Brak komentarzy.</p>'}</section>`;}\nfunction authCard(title,content){document.title=title+' · '+brand();",
'public portal views');
app=once(app,
"  if(view==='mfa'){S.mfaChallenge=key;return mfaLoginView();}\n  if(!S.user){applyTheme();return loginView();}",
"  if(view==='mfa'){S.mfaChallenge=key;return mfaLoginView();}\n  if(!S.user&&portalPath){S.portalMode=true;applyTheme();portalShell();try{const content=view==='ticket'&&key?await publicProjectTicketView(key):await publicProjectPortalView();if(id===S.routeId)$('#main').innerHTML=content;}catch(err){if(id===S.routeId)$('#main').innerHTML=`<div class=\"empty\"><h1>Nie udało się wczytać publicznego portalu</h1><p>${e(err.message)}</p></div>`;}return;}\n  if(!S.user){applyTheme();return loginView();}",
'anonymous portal routing');
write('public/app.js',app);

for(const p of ['lib/version.mjs','package.json','package-lock.json','public/index.html','public/settings-center.js','public/settings-nav-complete.js']){
  let s=read(p);s=replaceAllCount(s,'1.1.0','1.1.1',1,`${p} version`);write(p,s);
}

const test=`import test from 'node:test';\nimport assert from 'node:assert/strict';\nimport {readFileSync} from 'node:fs';\nimport {fixture} from './fixture.mjs';\nimport {migrateV8} from '../lib/migration-v8.mjs';\n\nconst source=p=>readFileSync(new URL('../'+p,import.meta.url),'utf8');\nfunction addUser(f,email,{ssoOnly=1,github=true}={}){\n  const id=Number(f.db.prepare(\"INSERT INTO users(email,name,username,password,role,must_change,active,sso_only,created_at) VALUES(?,?,?,?, 'customer',0,1,?,?)\").run(email,email,email.split('@')[0],'!test',ssoOnly,new Date().toISOString()).lastInsertRowid);\n  if(github){const provider=Number(f.db.prepare(\"INSERT INTO sso_providers(name,issuer,client_id,secret,config,enabled) VALUES('GitHub','https://github.com/','x','x','{}',1)\").run().lastInsertRowid);f.db.prepare('INSERT INTO sso_subjects(provider_id,subject,user_id) VALUES(?,?,?)').run(provider,String(1000+id),id);}\n  return f.db.prepare('SELECT * FROM users WHERE id=?').get(id);\n}\n\ntest('public GitHub project is readable publicly but write access is GitHub-authenticated and project-scoped',()=>{const f=fixture();try{migrateV8(f.db);const pub=f.projects.create({key:'PUB',name:'Public GitHub',project_type:'external',portal_access:'public_github'},f.admin),normal=f.projects.create({key:'SEC',name:'Authenticated portal',project_type:'external',portal_access:'authenticated'},f.admin),gh=addUser(f,'gh@example.test'),plain=addUser(f,'plain@example.test',{github:false,ssoOnly:0});assert.equal(f.projects.publicReadable(f.projects.project(pub.id)),true);assert.equal(f.projects.publicReadable(f.projects.project(normal.id)),false);assert.equal(f.projects.canPortal(gh,f.projects.project(pub.id)),true);assert.equal(f.projects.canPortal(gh,f.projects.project(normal.id)),false);assert.equal(f.projects.canPortal(plain,f.projects.project(pub.id)),false);assert.equal(f.projects.canPortal(plain,f.projects.project(normal.id)),true);f.db.prepare(\"INSERT INTO project_members(project_id,user_id,role) VALUES(?,?,'requester')\").run(normal.id,gh.id);assert.equal(f.projects.canPortal(gh,f.projects.project(normal.id)),true);}finally{f.close();}});\n\ntest('public GitHub portal exposes read-only anonymous API and GitHub login UI without public write endpoint',()=>{const server=source('server.mjs'),app=source('public/app.js'),projects=source('lib/projects.mjs');assert.match(projects,/public_github/);assert.match(server,/\\/api\\/public\\/portals/);assert.match(server,/c\\.internal=0/);assert.doesNotMatch(server,/method==='POST'&&publicPortal/);assert.match(app,/Zaloguj przez GitHub, aby utworzyć zgłoszenie/);assert.match(app,/Zaloguj przez GitHub, aby skomentować/);assert.match(app,/publicProjectTicketView/);});\n`;
write('tests/public-github-project.test.mjs',test);

const notes=`# Service Desk 1.1.1\n\n## Public GitHub projects\n\n- External projects can use **Public GitHub** portal access: anonymous visitors may browse tickets and public comments.\n- Creating tickets and adding comments still uses the authenticated Service Desk API and requires GitHub SSO for GitHub-only users.\n- GitHub-only SSO accounts no longer inherit access to every project configured as \"all authenticated users\". They are limited to Public GitHub projects plus projects where they have explicit membership.\n- Public responses intentionally omit internal notes, private custom fields, SLA internals, e-mail addresses, assignees, organizations and audit/activity history.\n\nDatabase schema remains **8**. No migration is required.\n`;
write('RELEASE_NOTES_1.1.1.md',notes);
console.log('Applied Service Desk 1.1.1 public GitHub project mode.');
